export namespace AiMpcaType {
  type Opt<T extends keyof typeof options> = keyof (typeof options)[T]

  export interface Type {
    'Reporting Organization': Opt<'Reporting Organization'>,
    'Implementing Partner': Opt<'Implementing Partner'>,
    'Activity Plan Code': Opt<'Activity Plan Code'>,
    'Donor': Opt<'Donor'>,
    'Indicators - MPCA'?: Opt<'Indicators - MPCA'>,
    'Total amount (USD) distributed through multi-purpose cash assistance': number,
    'Payments Frequency': Opt<'Payments Frequency'>,
    'Financial Service Provider (FSP)': Opt<'Financial Service Provider (FSP)'>,
    'Response Theme': Opt<'Response Theme'>,
    'Raion'?: string,
    'Hromada': string,
    'Settlement'?: string,
    'Collective Site'?: string,
    'Reporting Month': string,
    'Activity Start Month'?: string,
    'Activity End Month'?: string,
    'Number of Covered Months': Opt<'Number of Covered Months'>,
    'Population Group': Opt<'Population Group'>,
    'Total Individuals Reached': number,
    'Girls (0-17)': number,
    'Boys (0-17)': number,
    'Adult Women (18-59)': number,
    'Adult Men (18-59)': number,
    'Older Women (60+)': number,
    'Older Men (60+)': number,
    'People with disability': number,
    'Girls with disability (0-17)'?: number,
    'Boys with disability (0-17)'?: number,
    'Adult Women with disability (18-59)'?: number,
    'Adult Men with disability (18-59)'?: number,
    'Older Women with disability (60+)'?: number,
    'Older Men with disability (60+)'?: number
  }

  export const map = (a: Type) => ({
    'cw67b3nlq6so74pf': a['Reporting Organization'] === undefined ? undefined : 'czbgrslpwg36j52' + ':' + options['Reporting Organization'][a['Reporting Organization']!],
    'c53wwymlq6so74pg': a['Implementing Partner'] === undefined ? undefined : 'czbgrslpwg36j52' + ':' + options['Implementing Partner'][a['Implementing Partner']!],
    'cxzc3wylqxzrn9i2': a['Activity Plan Code'] === undefined ? undefined : 'c80149tlqm62xpv1tk' + ':' + options['Activity Plan Code'][a['Activity Plan Code']!],
    'cmuq05dlqnsj7yqf': a['Donor'] === undefined ? undefined : 'cf9uxrylqf1ttfc2' + ':' + options['Donor'][a['Donor']!],
    'ckv9joulsvxoptn2': a['Indicators - MPCA'] === undefined ? undefined : 'cid2wxslqb3pzob9e' + ':' + options['Indicators - MPCA'][a['Indicators - MPCA']!],
    'c9aasnglqnsgaq6e': a['Total amount (USD) distributed through multi-purpose cash assistance'] === undefined ? undefined : a['Total amount (USD) distributed through multi-purpose cash assistance'],
    'cakkhd9lqntdpktd': a['Payments Frequency'] === undefined ? undefined : options['Payments Frequency'][a['Payments Frequency']!],
    'cjrs9bzlr0f2x6wd': a['Financial Service Provider (FSP)'] === undefined ? undefined : options['Financial Service Provider (FSP)'][a['Financial Service Provider (FSP)']!],
    'cb7ml4clqnt87pf3': a['Response Theme'] === undefined ? undefined : options['Response Theme'][a['Response Theme']!],
    'cb39ganlqf3085j4z': a['Raion'] === undefined ? undefined : 'cd5q9sdlq3kklo314' + ':' + a['Raion'],
    'cmdrqq8lqf3085j50': a['Hromada'] === undefined ? undefined : 'cwlaxxlq3kp2bu5a' + ':' + a['Hromada'],
    'cn43jajlqf3085j51': a['Settlement'] === undefined ? undefined : 'cfn5ltdlq3lbcb95w' + ':' + a['Settlement'],
    'cf2masdlq6so74qr': a['Collective Site'] === undefined ? undefined : a['Collective Site'],
    'cmol4qhlq6so74qv': a['Reporting Month'] === undefined ? undefined : a['Reporting Month'],
    'c4t8d0xlqz50e1e2': a['Activity Start Month'] === undefined ? undefined : a['Activity Start Month'],
    'c4aesi0lqz510nh3': a['Activity End Month'] === undefined ? undefined : a['Activity End Month'],
    'canw5vhlqntauao6': a['Number of Covered Months'] === undefined ? undefined : options['Number of Covered Months'][a['Number of Covered Months']!],
    'cf6hv4zlq6so74qz': a['Population Group'] === undefined ? undefined : 'cf8ig2alq6dbe8t2' + ':' + options['Population Group'][a['Population Group']!],
    'c8docc8lq6so74q12': a['Total Individuals Reached'] === undefined ? undefined : a['Total Individuals Reached'],
    'cxxa4fmlq6so74q13': a['Girls (0-17)'] === undefined ? undefined : a['Girls (0-17)'],
    'cihl0t2lq6so74q14': a['Boys (0-17)'] === undefined ? undefined : a['Boys (0-17)'],
    'cm5uwnwlq6so74q15': a['Adult Women (18-59)'] === undefined ? undefined : a['Adult Women (18-59)'],
    'csp8uxllq6so74q16': a['Adult Men (18-59)'] === undefined ? undefined : a['Adult Men (18-59)'],
    'cy3skbtlq6so74q17': a['Older Women (60+)'] === undefined ? undefined : a['Older Women (60+)'],
    'c91006ylq6so74r18': a['Older Men (60+)'] === undefined ? undefined : a['Older Men (60+)'],
    'cexzo0hlq6so74r19': a['People with disability'] === undefined ? undefined : a['People with disability'],
    'cll4mlllqp9p0mr4': a['Girls with disability (0-17)'] === undefined ? undefined : a['Girls with disability (0-17)'],
    'c3cim3lqp9pzl35': a['Boys with disability (0-17)'] === undefined ? undefined : a['Boys with disability (0-17)'],
    'cutta7glqp9qq8v6': a['Adult Women with disability (18-59)'] === undefined ? undefined : a['Adult Women with disability (18-59)'],
    'cyacnhzlqp9rkug7': a['Adult Men with disability (18-59)'] === undefined ? undefined : a['Adult Men with disability (18-59)'],
    'cyk1e6rlqp9s7sk8': a['Older Women with disability (60+)'] === undefined ? undefined : a['Older Women with disability (60+)'],
    'cwt6rrtlqp9sz659': a['Older Men with disability (60+)'] === undefined ? undefined : a['Older Men with disability (60+)']
  })

  export const options = {
    'Reporting Organization': {
      'Danish Refugee Council': 'cloyih3lpwhjdsu2r0'
    },
    'Implementing Partner': {
      'Danish Refugee Council': 'cloyih3lpwhjdsu2r0'
    },
    'Activity Plan Code': {},
    'Donor': {
      'ACT Alliance': 'cvkyilllqf1uylbd4',
      'AICM Ukraine': 'cjtjqpglqf1uylbd5',
      'ATB-Market': 'cxbirpslqf1uylbd6',
      'AWO International': 'cwnz6rdlqf1uylbd7',
      'Adventist Development and Relief Agency Ukraine': 'ce4jer8lqf1uylbd8',
      'Adventist Development and Relief Agency Australia': 'cabgdowlqf1uylbd9',
      'Adventist Development and Relief Agency Austria': 'cpwsqsrlqf1uylbda',
      'Adventist Development and Relief Agency Belgium': 'cs2u9lwlqf1uylbdb',
      'Adventist Development and Relief Agency Canada': 'cvhk1otlqf1uylbdc',
      'Adventist Development and Relief Agency Denmark': 'ctrp07llqf1uylbdd',
      'Adventist Development and Relief Agency France': 'cwr2rpdlqf1uylbde',
      'Adventist Development and Relief Agency Inter-America Division': 'cgkcztrlqf1uylbdf',
      'Adventist Development and Relief Agency Netherlands': 'calwybdlqf1uylbdg',
      'Adventist Development and Relief Agency Norway': 'cxroni7lqf1uylbdh',
      'Adventist Development and Relief Agency South America Division': 'ctge4ralqf1uylbdi',
      'Adventist Development and Relief Agency Spain': 'civ5yjlqf1uylbdj',
      'Adventist Development and Relief Agency Sweden': 'cr41ucplqf1uylbdk',
      'Adventist Development and Relief Agency Switzerland': 'cfs7rz3lqf1uylbdl',
      'Adventist Development and Relief Agency UK': 'c363d08lqf1uylbdm',
      'Agency for Technical Cooperation and Development': 'cwjcauslqf1uylbdn',
      'AirLight': 'ch0fueklqf1uylbdo',
      'Aktion Deutschland Hilft': 'c1bwc31lqf1uylbdp',
      'Alliance2015': 'c5br1pklqf1uylbdq',
      'American Red Cross': 'czesx6hlqf1uylbdr',
      'Americares': 'ckds5gmlqf1uylbds',
      'Arbeiter-Samariter-Bund Deutschland e.V.': 'c31tki7lqf1uylbdt',
      'Arche Nova': 'cd88powlqf1uylbdu',
      'Australia, Government of': 'cfuqhp6lqf1uylbdv',
      'Austria, Government of': 'cgfgxzglqf1uylbdw',
      'Austrian Red Cross': 'ck1umdblqf1uylbdx',
      'Belgium, Government of': 'cbgdvalqf1uylbdy',
      'British Embassy Kyiv': 'cbiighglqf1uylbdz',
      'Brot für die Welt': 'camrzojlqf1uylbe0',
      'Brücke Nach Kiew': 'chm03mylqf1uylbe1',
      'Bulgaria, Government of': 'c8tsxublqf1uylbe2',
      'Bureau of Conflict and Stabilization Operations': 'cqv37whlqf1uylbe3',
      'CADUS e.V. - Redefine Global Solidarity': 'cfjo22nlqf1uylbe4',
      'CORE': 'c863y56lqf1uylce5',
      'Canada, Government of': 'cd83ra5lqf1uylce6',
      'Canada-Ukraine Foundation': 'cgwdscelqf1uylce7',
      'Canadian Foodgrains Bank': 'c8fzzkilqf1uylce8',
      'Caritas Austria': 'c4gdmo6lqf1uylce9',
      'Caritas Czech Republic': 'c362eqslqf1uylcea',
      'Caritas Germany': 'c9724sglqf1uylceb',
      'Caritas Internationalis': 'c1invaklqf1uylcec',
      'Caritas Poland': 'crakc68lqf1uylced',
      'Caritas Switzerland': 'ct0d24vlqf1uylcee',
      'Catholic Relief Services': 'cdozp6qlqf1uylcef',
      'Centers for Disease Control and Prevention': 'c73pbgdlqf1uylceg',
      'Central Emergency Response Fund': 'cu20rfolqf1uylceh',
      'ChildFund Deutschland': 'ccwpsk6lqf1uylcei',
      'ChildFund International': 'cf2zyo6lqf1uylcej',
      'Choose Love': 'cx0hh40lqf1uylcek',
      'Christian Aid': 'csjg3pflqf1uylcel',
      'Christian Blind Mission': 'c8us70jlqf1uylcem',
      'Christian Emergency Aid Cluster': 'c3t8efrlqf1uylcen',
      'Church in Action NL': 'cqtttb1lqf1uylceo',
      'Church in Action USA': 'c30btbtlqf1uylcep',
      'Coalition Plus': 'cagh6dglqf1uylceq',
      'Cooperating Aid Organizations': 'cg49esolqf1uylcer',
      'Corus International': 'cmkspuvlqf1uylces',
      'Council of Europe': 'cq447n7lqf1uylcet',
      'Crisis and Support Centre - French Ministry for Europe and Foreign Affairs': 'cszofjqlqf1uylceu',
      'Crown Agents International Development': 'cy1m86lqf1uylcev',
      'Cyprus, Government of': 'cw1s6ndlqf1uylcew',
      'Czech Republic, Government of': 'c4rg9vjlqf1uylcex',
      'DFID Consortium': 'cn6n7z8lqf1uylcey',
      'DRA': 'c9fea36lqf1uylcez',
      'DanChurchAid': 'c3ami7lqf1uylcf0',
      'Danish International Development Agency - Ministry of Foreign Affairs - Denmark': 'cevc6u8lqf1uyldf1',
      'Danish People\'s Aid': 'cv36n7jlqf1uyldf2',
      'Danish Refugee Council': 'c9jdb9xlqf1uyldf3',
      'Delegation of the European Union to Ukraine': 'cu62mn0lqf1uyldf4',
      'Denmark, Government of': 'c3rcxdxlqf1uyldf5',
      'Directorate General for Development Cooperation of the Ministry of Foreign Affairs and International Cooperation - Italy': 'caecybqlqf1uyldf6',
      'Disasters Emergency Committee': 'ca9wtq0lqf1uyldf7',
      'Dnipropetrovsk Regional Center of Psychosocial Support': 'cf7jwmelqf1uyldf8',
      'Development Center': 'cgfosbmlqf1uyldf9',
      'Dutch Relief Alliance': 'c58wcwklqf1uyldfa',
      'EPAM Systems': 'c8ncfiplqf1uyldfb',
      'EU Advisory Mission': 'cln193qlqf1uyldfc',
      'EU TA projects': 'c5rqll9lqf1uyldfd',
      'Education Cannot Wait': 'c9idmpklqf1uyldfe',
      'Embassy of Canada to Ukraine': 'c4vb9wplqf1uyldff',
      'Estonia, Government of': 'c4y8kq4lqf1uyldfg',
      'Estonian Refugee Council': 'ckd5913lqf1uyldfh',
      'Euro-Plus': 'ch8oee6lqf1uyldfi',
      'European Commission Humanitarian Aid Department and Civil Protection': 'cc3gaj6lqf1uyldfj',
      'European Commission\'s Directorate-General for European Civil Protection and Humanitarian Aid Operations': 'cgjlouwlqf1uyldfk',
      'European Programme for Integration and Migration': 'cc4axxjlqf1uyldfl',
      'European Union': 'ct2gxm8lqf1uyldfm',
      'FHI 360': 'cibl0ytlqf1uyldfn',
      'Faith, Hope, Love': 'ctpdd0ylqf1uyldfo',
      'Federal Agency for Technical Relief': 'c7pyz3slqf1uyldfp',
      'Federal Ministry for Economic Cooperation and Development - Germany': 'cwi9aj9lqf1uyldfq',
      'Federal Public Service Foreign Affairs, Foreign Trade and Development Cooperation - Belgium': 'co5kbbplqf1uyldfr',
      'Finland, Government of': 'cuytai8lqf1uyldfs',
      'First Ukrainian International Bank': 'cxqob0glqf1uyldft',
      'Foreign, Commonwealth & Development Office': 'cgxr4t2lqf1uyldfu',
      'Forest Initiatives and Communities': 'c3dl4q3lqf1uyldfv',
      'France, Government of': 'cu7um3slqf1uyldfw',
      'Fuel Relief Fund': 'crxdd7clqf1uyldfx',
      'GOAL': 'ce0ewy7lqf1uyldfy',
      'Gender Creative Space': 'c5bwbutlqf1uyldfz',
      'German Agency for International Cooperation': 'c52h1wylqf1uyldg0',
      'German Doctors e.V.': 'c5r4h6hlqf1uyldg1',
      'German Federal Foreign Office': 'c155drlqf1uyldg2',
      'Germany, Government of': 'cukmoo4lqf1uyldg3',
      'Global Affairs Canada': 'cup4td3lqf1uyldg4',
      'Global Empowerment Mission': 'c5e8hielqf1uyldg5',
      'Global Response Medicine': 'c1v2pghlqf1uyldg6',
      'Global Sae-A': 'cjn967nlqf1uyldg7',
      'Google': 'ctsfrqvlqf1uyldg8',
      'HEKS/EPER Swiss Church Aid': 'cl0t4rulqf1uyldg9',
      'Hebrew Immigrant Aid Society': 'cbnkkhnlqf1uyldga',
      'HelpAge Canada': 'cqpjrd2lqf1uyldgb',
      'HelpAge International Ukraine': 'cdxewzclqf1uyldgc',
      'Helvetas Swiss Intercooperation': 'c5g8bgilqf1uylegd',
      'High-net-worth individual': 'cv06ef7lqf1uylege',
      'Humanity & Inclusion': 'cykqw2lqf1uylegf',
      'Hungary, Government of': 'caxmmkglqf1uylegg',
      'IKEA': 'c7lubulqf1uylegh',
      'INTERSOS': 'co2nqswlqf1uylegi',
      'Iceland, Government of': 'cbtpbuflqf1uylegj',
      'International Committee of the Red Cross': 'c8upptelqf1uylegk',
      'International Federation of Red Cross and Red Crescent Societies': 'cfqi5fslqf1uylegl',
      'International Media Support': 'cf33k59lqf1uylegm',
      'International Medical Corps': 'c5xtct0lqf1uylegn',
      'International Organization for Migration': 'cmsdkg1lqf1uylego',
      'International Renaissance Foundation': 'cvvtqtulqf1uylegp',
      'International Rescue Committee': 'cui331elqf1uylegq',
      'International Research & Exchanges Board': 'chb39fxlqf1uylegr',
      'International Society for Human Rights': 'cjbvrxtlqf1uylegs',
      'Internationale Gesellschaft für Menschenrechte': 'crum7nllqf1uylegt',
      'Ireland, Government of': 'crmlc13lqf1uylegu',
      'Irish Aid - Department of Foreign Affairs - Ireland': 'c8zvg32lqf1uylegv',
      'Italian Agency for Development Cooperation': 'ca6e1htlqf1uylegw',
      'Italy, Government of': 'csm25mclqf1uylegx',
      'Japan International Cooperation Agency': 'cz1sy5llqf1uylegy',
      'Japan Platform': 'ckknd21lqf1uylegz',
      'Japan, Government of': 'clo52jqlqf1uyleh0',
      'Johanniter International Assistance': 'ckyafnhlqf1uyleh1',
      'Joint Distribution Committee': 'cg7ojqylqf1uyleh2',
      'Joint Emergency Response in Ukraine': 'cr4xnoxlqf1uyleh3',
      'KIA Foundation': 'ch2bcchlqf1uyleh4',
      'Kidsave International': 'crmo228lqf1uyleh5',
      'King Baudouin Foundation': 'cna7voxlqf1uyleh6',
      'Kingdom of the Netherlands': 'cunsoyllqf1uyleh7',
      'Korea Foundation for International Healthcare': 'cihple5lqf1uyleh8',
      'Korea, Republic of, Government of': 'c1u51jqlqf1uyleh9',
      'Kuwait, Government of': 'cx8iqhllqf1uyleha',
      'LEGO Foundation': 'c4h4kdjlqf1uylehb',
      'Latvia, Government of': 'cahjp51lqf1uylehc',
      'Leroy Merlin': 'c6b01tqlqf1uylehd',
      'Lithuania, Government of': 'ch6kl6vlqf1uylehe',
      'Luxembourg Red Cross': 'ci8b4lqlqf1uylehf',
      'Luxembourg, Government of': 'cze5845lqf1uylehg',
      'Malta, Government of': 'ccfmojqlqf1uylehh',
      'Malteser International': 'c922fuflqf1uylehi',
      'Medair': 'c85iflrlqf1uylehj',
      'Medecins Sans Frontieres Spain': 'cnn72jwlqf1uylehk',
      'Medecins du Monde Canada': 'c38ipq5lqf1uylehl',
      'Mental Health for Ukraine': 'c5kr44tlqf1uylehm',
      'Mercy Corps': 'c42g3wblqf1uylehn',
      'Migrant Offshore Aid Station': 'cfcy0iclqf1uyleho',
      'Ministry for Europe and Foreign Affairs - France': 'c99fuc7lqf1uylehp',
      'Ministry of Foreign Affairs - Denmark': 'cpexwoplqf1uylehq',
      'Ministry of Foreign Affairs - Estonia': 'cz3lgrnlqf1uylehr',
      'Ministry of Foreign Affairs - Finland': 'clf1n00lqf1uylehs',
      'Ministry of Foreign Affairs - Japan': 'cyqhg1rlqf1uyleht',
      'Ministry of Foreign Affairs - Netherlands': 'ckp87o2lqf1uylehu',
      'Ministry of Foreign Affairs - Norway': 'c7oxkgdlqf1uylehv',
      'Ministry of Foreign Affairs - Sweden': 'c4bkdi2lqf1uylfhw',
      'Ministry of Foreign Affairs and International Cooperation - Italy': 'c5hqd3klqf1uylfhx',
      'Ministry of Foreign Affairs of the Czech Republic': 'cu69zjylqf1uylfhy',
      'Mission East': 'cqwrw2slqf1uylfhz',
      'Monaco, Government of': 'cuj0hg8lqf1uylfi0',
      'Move Ukraine': 'cxdgduelqf1uylfi1',
      'National Endowment for Democracy': 'c3kztu4lqf1uylfi2',
      'NetJets': 'cn8yamqlqf1uylfi3',
      'Netherlands, Government of': 'ccuof70lqf1uylfi4',
      'New Apostolic Church': 'cdy2xevlqf1uylfi5',
      'New Zealand, Government of': 'c4mb17ulqf1uylfi6',
      'Nippon International Cooperation for Community Development': 'crtxaq9lqf1uylfi7',
      'Nonviolent Peaceforce': 'ccrohn5lqf1uylfi8',
      'Norway, Government of': 'cwtzjhslqf1uylfi9',
      'Norwegian Church Aid': 'crcfsdulqf1uylfia',
      'Norwegian People\'s Aid': 'cmna78tlqf1uylfib',
      'Norwegian Red Cross': 'c5m5bktlqf1uylfic',
      'Norwegian Refugee Council': 'c9v889blqf1uylfid',
      'OM International': 'cjk1q8klqf1uylfie',
      'Oak Foundation': 'cqox59ulqf1uylfif',
      'Office for Foreign Affairs - Principality of Liechtenstein': 'cnzzoc7lqf1uylfig',
      'Office of Weapons Removal and Abatement in the U.S. State Department’s Bureau of Political-Military Affairs': 'c9jcxxflqf1uylfih',
      'Office the Ukrainian Parliament Commissioner for Human Rights': 'cvt9vd3lqf1uylfii',
      'Ole Kirk\'s Foundation': 'ca7mk36lqf1uylfij',
      'Omaze': 'ca3m6oalqf1uylfik',
      'Oxfam International': 'c7b7wqilqf1uylfil',
      'PMU InterLife': 'cglosazlqf1uylfim',
      'Peace Winds Japan': 'cw32zi1lqf1uylfin'
    },
    'Indicators - MPCA': {
      '# of individuals assisted with multi-purpose cash assistance': 'cyj5n1elqb3qh9ba5',
      '# amount (USD) distributed through multi-purpose cash assistance': 'c7vtwjhlqb3qh9ba6',
      '% of households who report being able to meet their basic needs as they define and prioritize them': 'cd0hscblqb3qh9ba7',
      '% of recipients (disaggregated by sex, age, and disability) reporting that humanitarian assistance is delivered in a safe manner': 'c92m9uflqb3qh9ba8',
      '% of recipients (disaggregated by sex, age, and disability) reporting that humanitarian assistance is delivered in an accessible manner': 'czn5galqb3qh9ba9',
      '% of essential needs covered per sector': 'c64d3uwlqb3qh9baa',
      '% of recipients (disaggregated by sex, age, and disability) reporting that humanitarian assistance is delivered in a timely manner': 'c5at5eelqb3qh9bab'
    },
    'Payments Frequency': {
      'One-off': 'c22oxp8lqntdpktc',
      'Multiple payments': 'cigkge6lqnteihce'
    },
    'Financial Service Provider (FSP)': {
      'Bank Transfer': 'crpccsqlr0f2x6wc',
      'Digital Wallets': 'cqsen3tlsljp7rz8',
      'MoneyGram': 'cqfsd11lr0f5bzgf',
      'Private Post Office': 'ckvdcjxlr0f5vavh',
      'Ukrposhta (delivery)': 'c83wejdlsljok6h7',
      'Ukrposhta (pick up)': 'c56c4rhlr0f5hrkg',
      'Western Union': 'ca6qhyclr0f569te'
    },
    'Response Theme': {
      'No specific theme': 'clx2juzlqnt87pe2'
    },
    'Number of Covered Months': {
      'One month': 'czbonyjlqntauao5',
      'Two months': 'cokxxzhlqntc71k7',
      'Three months (recommended)': 'c6s6jv3lqntc9ua8',
      'Four months': 'cab6to9lqntckcz9',
      'Five months': 'ctsl3i3lqntco52a',
      'Six months': 'cwqi52ylqntcx15b'
    },
    'Population Group': {
      'Internally Displaced': 'cvw4on6lq6dgcoj5',
      'Non-Displaced': 'ck6ulx8lq6dgcok6',
      'Returnees': 'cuz9qi9lq6dgcok7'
    }
  }
}