export type AiOblast = keyof typeof aiOblasts

export const aiOblasts = {
  "Autonomous Republic of Crimea_Автономна Республіка Крим": 'c5c2sr3lq3kjj6gd',
  "Cherkaska_Черкаська": 'clbgltvlq3kjj6he',
  "Chernihivska_Чернігівська": 'c7jz1shlq3kjj6hf',
  "Chernivetska_Чернівецька": 'c78zq2rlq3kjj6hg',
  "Dnipropetrovska_Дніпропетровська": 'c6l0fjylq3kjj6hh',
  "Donetska_Донецька": 'c3memjqlq3kjj6hi',
  "Ivano-Frankivska_Івано-Франківська": 'cy93k5lq3kjj6hj',
  "Kharkivska_Харківська": 'cbbcx5ylq3kjj6hk',
  "Khersonska_Херсонська": 'cq8k2oylq3kjj6hl',
  "Khmelnytska_Хмельницька": 'cliunu3lq3kjj6hm',
  "Kirovohradska_Кіровоградська": 'cxvw276lq3kjj6hn',
  "Kyiv_Київ": 'cwe11jplq3kjj6ho',
  "Kyivska_Київська": 'cnp046mlq3kjj6hp',
  "Luhanska_Луганська": 'ctu8ahklq3kjj6hq',
  "Lvivska_Львівська": 'cmpyidslq3kjj6hr',
  "Mykolaivska_Миколаївська": 'ccqvlallq3kjj6hs',
  "Odeska_Одеська": 'c2uwqqqlq3kjj6ht',
  "Poltavska_Полтавська": 'cwq2uuxlq3kjj6hu',
  "Rivnenska_Рівненська": 'c2j0t0flq3kjj6hv',
  "Sevastopol_Севаaiстополь": 'cjvbpkplq3kjj6hw',
  "Sumska_Сумська": 'cb4nm4xlq3kjj6hx',
  "Ternopilska_Тернопільська": 'clrrzfslq3kjj6hy',
  "Vinnytska_Вінницька": 'cvx17yllq3kjj6hz',
  "Volynska_Волинська": 'cdzklrblq3kjj6h10',
  "Zakarpatska_Закарпатська": 'cfqiux5lq3kjj6h11',
  "Zaporizka_Запорізька": 'cmqvx7elq3kjj6h12',
  "Zhytomyrska_Житомирська": 'c51dllnlq3kjj6h13'
}
