export type AiWashType = AiWashType.Type

export namespace AiWashType {
  type Opt<T extends keyof typeof options> = keyof (typeof options)[T]

  export interface Type {
    'Plan/Project Code': Opt<'WASH APM 2025'>
    'Reporting Organization': Opt<'Partner'>
    'Implementing Partner'?: Opt<'Partner'>
    Donor?: Opt<'Donor'>
    Indictors: Opt<'Indicators - WASH'>
    Theme?: Opt<'Theme'>
    Oblast: string
    Raion: string
    Hromada: string
    Settlement: string
    'Type of institution / Beneficiary': Opt<'Type of institution / Beneficiary'>
    'Facility Name'?: string
    'Reporting Month': string
    'Activity Start month'?: string
    'Activity End month'?: string
    'Is the disaggregation by population group, gender and age known?': Opt<'Is the disaggregation by population group, gender and age known?'>
    'Total Reached (No Disaggregation)': number
    'Population Group': Opt<'Population Group'>
    'Girls (0-17)': number
    'Boys (0-17)': number
    'Adult Women (18-59)': number
    'Adult Men (18-59)': number
    'Older Women (60+)': number
    'Older Men (60+)': number
    /**
     Out of the total individuals reached
     */
    'People with disability'?: number
    'Name of items/services delivered'?: string
    'Quantity of items/services delivered'?: number
    Comments?: string
    'HNRP Scope'?: Opt<'HNRP Scope'>
    'Outside HNRP Scope sub-category'?: Opt<'Outside HNRP Scope categories'>
  }

  export const buildRequest = (a: Type, recordId: string, parentRecordId: string | null = null) => {
    return [
      {
        formId: 'czg50xvm6an62wz2',
        recordId,
        parentRecordId,
        fields: {
          ckha5hmm6anb4ox4: a['Plan/Project Code']
            ? 'c3skhwjm5l0iiy52' + ':' + options['WASH APM 2025'][a['Plan/Project Code']!]
            : undefined,
          ccf86g8m6ann72c3: a['Reporting Organization']
            ? 'cideet6m4jy2m0fy3x' + ':' + options['Partner'][a['Reporting Organization']!]
            : undefined,
          cvgfaxrm6anoubg4: a['Implementing Partner']
            ? 'cideet6m4jy2m0fy3x' + ':' + options['Partner'][a['Implementing Partner']!]
            : undefined,
          c24f2xmm6anw1206: a['Donor'] ? 'c3m2htlm4s9h25d16' + ':' + options['Donor'][a['Donor']!] : undefined,
          cq68acdm6ao0qwm7: a['Indictors']
            ? 'cywemjem4r94m7l196' + ':' + options['Indicators - WASH'][a['Indictors']!]
            : undefined,
          cmlg59mm6ao2j8b9: a['Theme'] ? options['Theme'][a['Theme']!] : undefined,
          cir7cxwm6ao6gyab: a['Oblast'] ? 'ciok70dm4r8lp7f2' + ':' + a['Oblast'] : undefined,
          cx21763m6ao80uuc: a['Raion'] ? 'c1v215km4s71ndl22' + ':' + a['Raion'] : undefined,
          cdr0ffm6ao9nc5d: a['Hromada'] ? 'cu8n0g0m4s7y2p16b' + ':' + a['Hromada'] : undefined,
          cywrf8mm6aobi3me: a['Settlement'] ? 'cyr4ry4m4s81hdd6v' + ':' + a['Settlement'] : undefined,
          cecsem8m6aof1cmg: a['Type of institution / Beneficiary']
            ? options['Type of institution / Beneficiary'][a['Type of institution / Beneficiary']!]
            : undefined,
          cyzwskcm6aoi2mup: a['Facility Name'],
          cmgpxd2m6aol5y6r: a['Reporting Month'],
          cggbhakm6aoo988s: a['Activity Start month'],
          cbav6csm6aoouvwt: a['Activity End month'],
          cbsx2d2m6aqfz5bw: a['Is the disaggregation by population group, gender and age known?']
            ? options['Is the disaggregation by population group, gender and age known?'][
                a['Is the disaggregation by population group, gender and age known?']!
              ]
            : undefined,
          ctvd758m6aqm0rwy: a['Total Reached (No Disaggregation)'],
          cwwmg44m6aqpk8dz: a['Population Group']
            ? 'cknn1yzm4s6xuox1x' + ':' + options['Population Group'][a['Population Group']!]
            : undefined,
          ciob248m6ar3rfy10: a['Girls (0-17)'],
          c28ur4lm6ar4l3l11: a['Boys (0-17)'],
          cd9s6nwm6ar5opy12: a['Adult Women (18-59)'],
          crd11mim6ar6nhz13: a['Adult Men (18-59)'],
          cwo9ijxm6ar7jo514: a['Older Women (60+)'],
          cqd2pcim6ar8n9r15: a['Older Men (60+)'],
          c8yuk0m6ar9q2q16: a['People with disability'],
          cut5jxam6ghn2xv3: a['Name of items/services delivered'],
          c2vdeg0m6ghnxki4: a['Quantity of items/services delivered'],
          c6oiwvzm6hr5puy2: a['Comments'],
          cwhkykam6f3aa9u4: a['HNRP Scope'] ? options['HNRP Scope'][a['HNRP Scope']!] : undefined,
          c4fo3dem6f3c4nn5: a['Outside HNRP Scope sub-category']
            ? 'ch0e182m4vgc05r2' + ':' + options['Outside HNRP Scope categories'][a['Outside HNRP Scope sub-category']!]
            : undefined,
        },
      },
    ]
  }

  export const options = {
    'WASH APM 2025': {'WASH-DRC-00001': 'c5jceofm7xgsnhy8', 'WASH-DRC-00002': 'ceb3t45m7z5hqhv2'},
    Partner: {'Danish Refugee Council (DRC)': 'cjmwszwm4s8hlkyrae'},
    Donor: {
      'ACT Alliance (ACT)': 'cei9dbm4s9iiu9cm',
      'AICM Ukraine (AICMUA)': 'clndct5m4s9iiu9cn',
      'ATB-Market (ATB)': 'c6nnr1am4s9iiu9co',
      'AWO International (AWO)': 'cp5pf45m4s9iiu9cp',
      'Adventist Development and Relief Agency Ukraine (ADRA Ukraine)': 'ctly2yqm4s9iiu9cq',
      'Adventist Development and Relief Agency Australia (ADRA Australia)': 'cw505g3m4s9iiuacr',
      'Adventist Development and Relief Agency Austria (ADRA Austria)': 'c5yx6hqm4s9iiuacs',
      'Adventist Development and Relief Agency Belgium (ADRA Belgium)': 'cwf0qntm4s9iiuact',
      'Adventist Development and Relief Agency Canada (ADRA Canada)': 'cejb7txm4s9iiuacu',
      'Adventist Development and Relief Agency Denmark (ADRA Denmark)': 'ckz4z1am4s9iiuacv',
      'Adventist Development and Relief Agency France (ADRA France)': 'cm8tzdom4s9iiuacw',
      'Adventist Development and Relief Agency Inter-American Division (ADRA IAD)': 'clz6opqm4s9iiuacx',
      'Adventist Development and Relief Agency Netherlands (ADRA Netherlands)': 'cnmslh9m4s9iiuacy',
      'Adventist Development and Relief Agency Norway (ADRA Norway)': 'c8ixmaqm4s9iiuacz',
      'Adventist Development and Relief Agency South America Division (ADRA South America Division)':
        'c9i82sem4s9iiuad0',
      'Adventist Development and Relief Agency Spain (ADRA Spain)': 'camfk9gm4s9iiuad1',
      'Adventist Development and Relief Agency Sweden (ADRA Sweden)': 'c40voedm4s9iiuad2',
      'Adventist Development and Relief Agency Switzerland (ADRA Switzerland)': 'c9ub71zm4s9iiuad3',
      'Adventist Development and Relief Agency UK (ADRA UK)': 'c4eu6x7m4s9iiuad4',
      'Agency for Technical Cooperation and Development (ACTED)': 'ci1dk2wm4s9iiuad5',
      'AirLight (AirLight)': 'cm1yigzm4s9iiuad6',
      'Aktion Deutschland Hilft (ADH)': 'c98gw0om4s9iiuad7',
      'Alliance2015 (Alliance2015)': 'cmk5czim4s9iiuad8',
      'American Red Cross (ARC)': 'c9t0mzhm4s9iiuad9',
      'Americares (Americares)': 'c98r9qem4s9iiuada',
      'Arbeiter-Samariter-Bund Deutschland e.V. (ASB)': 'c6y8ctm4s9iiuadb',
      'Arche Nova (AN)': 'cquvtw0m4s9iiuadc',
      'Australia, Government of (Australia)': 'c1t1uaxm4s9iiuadd',
      'Austria, Government of (Austria)': 'cmg4ktzm4s9iiuade',
      'Austrian Red Cross (ORK)': 'ce1fgyom4s9iiuadf',
      'Belgium, Government of (Belgium)': 'cxr9c16m4s9iiuadg',
      'British Embassy Kyiv (UKEmbassy)': 'cz81k2qm4s9iiubdh',
      'Brot fur die Welt (BfW)': 'cafom41m4s9iiubdi',
      'Brucke Nach Kiew (Brucke)': 'ch6uuz7m4s9iiubdj',
      'Bulgaria, Government of (Bulgaria)': 'ce4xjrcm4s9iiubdk',
      'Bureau of Conflict and Stabilization Operations (CSO)': 'c1oplsdm4s9iiubdl',
      'CADUS e.V. - Redefine Global Solidarity (CADUS)': 'cs6u12xm4s9iiubdm',
      'CORE (CORE)': 'chlwv37m4s9iiubdn',
      'Canada, Government of (Canada)': 'clp620dm4s9iiubdo',
      'Canada-Ukraine Foundation (CUFOUNDATION)': 'c3r7n5m4s9iiubdp',
      'Canadian Foodgrains Bank (CFGB)': 'cbdkdmdm4s9iiubdq',
      'Caritas Austria (CaritasAT)': 'chh7t94m4s9iiubdr',
      'Caritas Czech Republic (CaritasCZE)': 'cypjgblm4s9iiubds',
      'Caritas Germany (DCV)': 'cya25i6m4s9iiucdt',
      'Caritas Internationalis (CaritasInt)': 'c35j2aim4s9iiucdu',
      'Caritas Poland (CaritasPL)': 'cv1yfwnm4s9iiucdv',
      'Caritas Switzerland (CaritasCH)': 'c8x43c2m4s9iiucdw',
      'Catholic Relief Services (CRS)': 'ccw1ffgm4s9iiucdx',
      'Centers for Disease Control and Prevention (CDC)': 'cce7jlfm4s9iiucdy',
      'Central Emergency Response Fund (CERF)': 'ck9iuhjm4s9iiucdz',
      'ChildFund Deutschland (CFDE)': 'c2mm4lm4s9iiuce0',
      'ChildFund International (CFI)': 'cxqdy0pm4s9iiuce1',
      'Choose Love (CHL)': 'c9w3t8ym4s9iiuce2',
      'Christian Aid (CHRAid)': 'c99bfbmm4s9iiuce3',
      'Christian Blind Mission (CBM)': 'ck7d58vm4s9iiuce4',
      'Christian Emergency Aid Cluster (CNHC)': 'c8veitum4s9iiuce5',
      'Church in Action NL (KIA NL)': 'ct4m9q1m4s9iiuce6',
      'Church in Action USA (KIA USA)': 'cr8wr93m4s9iiuce7',
      'Coalition Plus (CoalitionPlus)': 'cdato1km4s9iiuce8',
      'Cooperating Aid Organizations (SHO)': 'cdxhq6dm4s9iiuce9',
      'Corus International (Corus)': 'cep2xi6m4s9iiucea',
      'Council of Europe (COE)': 'ctd7dolm4s9iiuceb',
      'Crisis and Support Centre - French Ministry for Europe and Foreign Affairs (CDCS/MEAE)': 'c60vxijm4s9iiucec',
      'Crown Agents International Development (CAID)': 'cxffc18m4s9iiuced',
      'Cyprus, Government of (Cyprus)': 'cuzlhs6m4s9iiucee',
      'Czech Republic, Government of (Czech Republic)': 'crv6krum4s9iiucef',
      'DFID Consortium (DFIDC)': 'c9v9mejm4s9iiuceg',
      'DRA (DRA)': 'c9cxavhm4s9iiuceh',
      'DanChurchAid (DCA)': 'cxv359jm4s9iiucei',
      'Danish International Development Agency - Ministry of Foreign Affairs - Denmark (DANIDA)': 'ch96v7bm4s9iiucej',
      "Danish People's Aid (DPA)": 'c16iz98m4s9iiucek',
      'Danish Refugee Council (DRC)': 'cdaselsm4s9iiucel',
      'Delegation of the European Union to Ukraine (EEAS)': 'cf4c50hm4s9iiucem',
      'Denmark, Government of (Denmark)': 'c72uhdcm4s9iiucen',
      'Directorate General for Development Cooperation of the Ministry of Foreign Affairs and International Cooperation - Italy (DGDC/MFA Italy)':
        'cx2sdiwm4s9iiudeo',
      'Disasters Emergency Committee (DEC)': 'ctgttasm4s9iiudep',
      'Dnipropetrovsk Regional Center of Psychosocial Support (DRCPS)': 'cqm8nj4m4s9iiudeq',
      'Development Center (DDC)': 'c4vkxslm4s9iiuder',
      'Dutch Relief Alliance (DutchRelief)': 'cda1nvlm4s9iiudes',
      'EPAM Systems (EPAM)': 'csghi6am4s9iiudet',
      'EU Advisory Mission (EUA)': 'cpkjhp0m4s9iiudeu',
      'EU TA projects (EUTA)': 'ca3hfpdm4s9iiudev',
      'Education Cannot Wait (ECW)': 'cwxf22om4s9iiudew',
      'Embassy of Canada to Ukraine (CAEmbassy)': 'cl2xqoym4s9iiudex',
      'Estonia, Government of (Estonia)': 'cz6i9edm4s9iiudey',
      'Estonian Refugee Council (ERC)': 'c14dfa5m4s9iiudez',
      'Euro-Plus (Euro+)': 'c30tjy7m4s9iiudf0',
      'European Commission Humanitarian Aid Department and Civil Protection (ECHO)': 'csn15j6m4s9iiudf1',
      "European Commission's Directorate-General for European Civil Protection and Humanitarian Aid Operations (DG ECHO)":
        'cns6k4cm4s9iiudf2',
      'European Programme for Integration and Migration (EPIM)': 'cwn1i4ym4s9iiudf3',
      'European Union (EU)': 'ckcg2k9m4s9iiudf4',
      'FHI 360 (FHI360)': 'c3gikdwm4s9iiudf5',
      'Faith, Hope, Love (FHL)': 'cwjl2lom4s9iiudf6',
      'Federal Agency for Technical Relief (THW Germany)': 'c1n04ygm4s9iiudf7',
      'Federal Ministry for Economic Cooperation and Development - Germany (BMZ)': 'cwkxllxm4s9iiudf8',
      'Federal Public Service Foreign Affairs, Foreign Trade and Development Cooperation - Belgium (MFA Belgium)':
        'c3ownqsm4s9iiudf9',
      'Finland, Government of (Finland)': 'cbckzqam4s9iiudfa',
      'First Ukrainian International Bank (PUMB)': 'c43n6rgm4s9iiuefb',
      'Foreign, Commonwealth & Development Office (FCDO)': 'c9av4rjm4s9iiuefc',
      'Forest Initiatives and Communities (ForestCom)': 'ciwrhgm4s9iiuefd',
      'France, Government of (France)': 'cq2zuntm4s9iiuefe',
      'Fuel Relief Fund (FRF)': 'c2s9ndsm4s9iiueff',
      'GOAL (GOAL)': 'cnkh7zpm4s9iiuefg',
      'Gender Creative Space (GСS)': 'cypg79tm4s9iiuefh',
      'German Agency for International Cooperation (GIZ)': 'cjtsbzcm4s9iiuefi',
      'German Doctors e.V. (GD)': 'clpcowjm4s9iiuefj',
      'German Federal Foreign Office (GFO)': 'cb5iyhom4s9iiuefk',
      'Germany, Government of (Germany)': 'cz360p7m4s9iiuefl',
      'Global Affairs Canada (GAC)': 'cb7n8gtm4s9iiuefm',
      'Global Empowerment Mission (GEM)': 'ccc4xs0m4s9iiuefn',
      'Global Response Medicine (GRM)': 'cl29qv8m4s9iiuefo',
      'Global Sae-A (Sae-A)': 'c3lohjlm4s9iiuefp',
      'Google (Google)': 'cm74w45m4s9iiuefq',
      'HEKS/EPER Swiss Church Aid (HEKS-EPER)': 'c4jnhlkm4s9iiuefr',
      'Hebrew Immigrant Aid Society (HIAS)': 'c649zu3m4s9iiuefs',
      'HelpAge Canada (HACA)': 'c8jg67km4s9iiueft',
      'HelpAge International Ukraine (HAIUA)': 'cilu07nm4s9iiuefu',
      'Helvetas Swiss Intercooperation (Helvetas)': 'c5rfrkwm4s9iiuefv',
      'High-net-worth individual (HNWI)': 'cd56bg2m4s9iiuefw',
      'Humanity & Inclusion (HI)': 'cii3jhym4s9iiuefx',
      'Hungary, Government of (Hungary)': 'cetmb52m4s9iiuefy',
      'IKEA (IKEA)': 'cq0lbozm4s9iiuefz',
      'INTERSOS (INTERSOS)': 'c1pxcbam4s9iiueg0',
      'Iceland, Government of (Iceland)': 'c2gq28fm4s9iiueg1',
      'International Committee of the Red Cross (ICRC)': 'ct54k0bm4s9iiueg2',
      'International Federation of Red Cross and Red Crescent Societies (IFRC)': 'cplmv83m4s9iiueg3',
      'International Media Support (IMS)': 'cy17en7m4s9iiufg4',
      'International Medical Corps (IMC)': 'ce3boeam4s9iiufg5',
      'International Organization for Migration (IOM)': 'cschsrvm4s9iiufg6',
      'International Renaissance Foundation (IRF)': 'cpkdqsim4s9iiufg7',
      'International Rescue Committee (IRC)': 'cghbopsm4s9iiufg8',
      'International Research & Exchanges Board (IREX)': 'cwsu40om4s9iiufg9',
      'International Society for Human Rights (ISHR)': 'cud1hym4s9iiufga',
      'Internationale Gesellschaft fur Menschenrechte (IGFM)': 'cwt8mw3m4s9iiufgb',
      'Ireland, Government of (Ireland)': 'clqnz0vm4s9iiufgc',
      'Irish Aid - Department of Foreign Affairs - Ireland (IrishAid)': 'c3elpt9m4s9iiufgd',
      'Italian Agency for Development Cooperation (AICS)': 'cpaj6g8m4s9iiufge',
      'Italy, Government of (Italy)': 'cok7qdzm4s9iiufgf',
      'Japan International Cooperation Agency (JICA)': 'cxii8p7m4s9iiufgg',
      'Japan Platform (JPF)': 'c9k4pgom4s9iiufgh',
      'Japan, Government of (Japan)': 'cj4ojfym4s9iiufgi',
      'Johanniter International Assistance (JIA)': 'cimjfsom4s9iiufgj',
      'Joint Distribution Committee (JDC)': 'coe0zu8m4s9iiufgk',
      'Joint Emergency Response in Ukraine (JERU)': 'crwid5sm4s9iiufgl',
      'KIA Foundation (KIA)': 'cvgply2m4s9iiufgm',
      'Kidsave International (Kidsave)': 'c4nhma0m4s9iiufgn',
      'King Baudouin Foundation (KBF)': 'cle8u5km4s9iiufgo',
      'Kingdom of the Netherlands (KN)': 'cxh82zdm4s9iiufgp',
      'Korea Foundation for International Healthcare (KOFIH)': 'cmcrp0im4s9iiufgq',
      'Korea, Republic of, Government of (Korea)': 'c2z205pm4s9iiufgr',
      'Kuwait, Government of (Kuwait)': 'cftih5um4s9iiufgs',
      'LEGO Foundation (LEGO)': 'corortom4s9iiufgt',
      'Latvia, Government of (Latvia)': 'c13n3fqm4s9iiufgu',
      'Leroy Merlin (LM)': 'cfa1si2m4s9iiuggv',
      'Lithuania, Government of (Lithuania)': 'c246wedm4s9iiuggw',
      'Luxembourg Red Cross (LRC)': 'c8m2iz0m4s9iiuggx',
      'Luxembourg, Government of (Luxembourg)': 'cls2gf4m4s9iiuggy',
      'Malta, Government of (Malta)': 'c37fnhem4s9iiuggz',
      'Malteser International (MI)': 'c7tx3vim4s9iiugh0',
      'Medair (Medair)': 'cye2nd1m4s9iiugh1',
      'Medecins Sans Frontieres Spain (MSF Spain)': 'clxfhjom4s9iiugh2',
      'Medecins du Monde Canada (MDM-CA)': 'c8eju28m4s9iiugh3',
      'Mental Health for Ukraine (MH4UA)': 'csu96plm4s9iiugh4',
      'Mercy Corps (MC)': 'c4lyhvcm4s9iiugh5',
      'Migrant Offshore Aid Station (MOAS)': 'cs8zevrm4s9iiugh6',
      'Ministry for Europe and Foreign Affairs - France (MEAE France)': 'cbvmuccm4s9iiugh7',
      'Ministry of Foreign Affairs - Denmark (MFA Denmark)': 'cvr0390m4s9iiugh8',
      'Ministry of Foreign Affairs - Estonia (MFA Estonia)': 'co3dxlam4s9iiugh9',
      'Ministry of Foreign Affairs - Finland (MFA Finland)': 'cv3waz3m4s9iiugha',
      'Ministry of Foreign Affairs - Japan (MFA Japan)': 'cbtyu2rm4s9iiughb',
      'Ministry of Foreign Affairs - Netherlands (MFA Netherlands)': 'c5ygq0bm4s9iiughc',
      'Ministry of Foreign Affairs - Norway (MFA Norway)': 'cyyvaam4s9iiughd',
      'Ministry of Foreign Affairs - Sweden (MFA Sweden)': 'c4oy5hym4s9iiughe',
      'Ministry of Foreign Affairs and International Cooperation - Italy (MFA Italy)': 'cbs8e4hm4s9iiughf',
      'Ministry of Foreign Affairs of the Czech Republic (MFA Czech)': 'cibaoojm4s9iiuhhg',
      'Mission East (MEast)': 'cwwszktm4s9iiuhhh',
      'Monaco, Government of (Monaco)': 'chtvytum4s9iiuhhi',
      'Move Ukraine (MU)': 'cvbxyctm4s9iiuhhj',
      'National Endowment for Democracy (NED)': 'chec9mem4s9iiuhhk',
      'NetJets (NetJets)': 'cmt73u4m4s9iiuhhl',
      'Netherlands, Government of (Netherlands)': 'co1gxdqm4s9iiuhhm',
      'New Apostolic Church (NAK)': 'czegz4sm4s9iiuhhn',
      'New Zealand, Government of (New Zealand)': 'cjoz5h2m4s9iiuhho',
      'Nippon International Cooperation for Community Development (NICCO)': 'cu38u41m4s9iiuhhp',
      'Nonviolent Peaceforce (NVPF)': 'ckmuhaqm4s9iiuhhq',
      'Norway, Government of (Norway)': 'cxspohvm4s9iiuhhr',
      'Norwegian Church Aid (NCA)': 'ccxk3t6m4s9iiuhhs',
      "Norwegian People's Aid (NPAID)": 'czqn8ym4s9iiuhht',
      'Norwegian Red Cross (NORC)': 'cm3odom4s9iiuhhu',
      'Norwegian Refugee Council (NRC)': 'cuyaojgm4s9iiuhhv',
      'OM International (OM International)': 'cbmuawpm4s9iiuhhw',
      'Oak Foundation (Oak)': 'cvzh9ffm4s9iiuhhx',
      'Office for Foreign Affairs - Principality of Liechtenstein (MFA Liechtenstein)': 'cwb3twqm4s9iiuhhy',
      'Office of Weapons Removal and Abatement in the U.S. State Department’s Bureau of Political-Military Affairs (PM/WRA)':
        'ct5sie2m4s9iiuhhz',
      'Office the Ukrainian Parliament Commissioner for Human Rights (Ombudsman)': 'cj0sgd0m4s9iiuhi0',
      "Ole Kirk's Foundation (OKF)": 'cbf3g7sm4s9iiuhi1',
      'Omaze (Omaze)': 'c5lhzcsm4s9iiuhi2',
      'Oxfam International (Oxfam)': 'ccchrgsm4s9iiuhi3',
      'PMU InterLife (PMU)': 'camuer8m4s9iiuhi4',
      'Peace Winds Japan (PWJ)': 'c9yj5ium4s9iiuhi5',
      'Pentecostal Union (PU)': 'clv9r2fm4s9ijd0i6',
      'People In Need (PIN)': 'can7iuwm4s9ijd1i7',
      'People in Peril (PIP)': 'c5oaj8m4s9ijd1i8',
      'Philip Morris International (PMI)': 'c12kkajm4s9ijd1i9',
      'Philippines, Government of (Philippines)': 'cj5baglm4s9ijd1ia',
      'Poland, Government of (Poland)': 'ce86jkdm4s9ijd1ib',
      'Polish Medical Mission (PMM)': 'c9dau1tm4s9ijd1ic',
      'Pomozi.ba (Pomozi.ba)': 'csdd04tm4s9ijd1id',
      'Portugal, Government of (Portugal)': 'cdueghdm4s9ijd1ie',
      'Premiere Urgence Internationale (PUI)': 'cme27trm4s9ijd1if',
      'Project Nadiya, USA (PNadiyaUS)': 'cospk4nm4s9ijd1ig',
      'RE/MAX (RE/MAX)': 'c5xirn4m4s9ijd1ih',
      'RKESA (RKESA)': 'cswz6gm4s9ijd1ii',
      'RTL Foundation (RTLF)': 'cmd7ooom4s9ijd1ij',
      "SOS Children's Villages (SOSCV)": 'cc0al0bm4s9ijd1ik',
      'Samaritan Association of Latvia (LSA)': 'ctjm2q7m4s9ijd1il',
      "Samaritan's Purse (SPIR)": 'ccedpq3m4s9ijd1im',
      'Save the Children (SCI)': 'cpojygvm4s9ijd1in',
      'Serbia, Government of (Serbia)': 'cdswmezm4s9ijd1io',
      'ShelterBox (SB)': 'ccjciqdm4s9ijd1ip',
      'Sign of Hope (SoH)': 'ckzsphxm4s9ijd1iq',
      'Slovakia, Government of (Slovakia)': 'cyo0r7mm4s9ijd2ir',
      'Slovenia, Government of (Slovenia)': 'c63udw5m4s9ijd2is',
      'Soleterre (Soleterre)': 'cv0fkpim4s9ijd2it',
      'Solidarites International (SI)': 'c6m5hwxm4s9ijd2iu',
      'Spain, Government of (Spain)': 'cag99swm4s9ijd2iv',
      'Stichting Vluchteling - Refugee Foundation (SV)': 'c68lkv0m4s9ijd2iw',
      'Sweden, Government of (Sweden)': 'cejjui6m4s9ijd2ix',
      'Swedish International Development Cooperation Agency (Sida)': 'c1qwyrfm4s9ijd2iy',
      'Swiss Agency for Development and Cooperation (SDC)': 'c4uq3iqm4s9ijd2iz',
      'Swiss Red Cross (SRC)': 'co7kngnm4s9ijd2j0',
      'Swiss Solidarity (Solidarity)': 'cie1ctum4s9ijd2j1',
      'Tearfund (TF)': 'c86bpbem4s9ijd3j2',
      'Thailand, Government of (Thailand)': 'coko6ogm4s9ijd3j3',
      'The Church of Jesus Christ of Latter-Day Saints (ChJC)': 'cvt4h38m4s9ijd3j4',
      'The Global Fund (GF)': 'crjq4vjm4s9ijd3j5',
      'Timor Leste, Government of (Timor Leste)': 'cdqq0xwm4s9ijd3j6',
      'Triangle Generation Humanitaire (Triangle)': 'ckqous6m4s9ijd3j7',
      'Tzu Chi Foundation (TzuChi)': 'cz46txm4s9ijd3j8',
      'U.S. Department of State (DoS)': 'c6zods5m4s9ijd3j9',
      "U.S. Department of State's Bureau of Population, Refugees, and Migration (PRM)": 'ce2sb6bm4s9ijd3ja',
      'UBS (UBS)': 'ctevzgfm4s9ijd3jb',
      'UN Women (UNW)': 'cp12i7zm4s9ijd3jc',
      'USAID / Disaster Assistance Response Team (DART)': 'cmb2t1em4s9ijd3jd',
      "USAID / U.S. Department of State's Bureau of Population, Refugees, and Migration (USAID-PRM)":
        'cox4g97m4s9ijd3je',
      'USAID Global Health Supply Chain Program (GHSC)': 'cc2uam0m4s9ijd3jf',
      "USAID's Bureau for Humanitarian Assistance (USAID/BHA)": 'c1vyg49m4s9ijd3jg',
      "USAID's Country Development Cooperation Strategies (CDCS-USAID)": 'ckot7ccm4s9ijd3jh',
      "USAID's Office of U.S. Foreign Disaster Assistance (USAID/OFDA)": 'c2mfo2fm4s9ijd3ji',
      'Ukraine Humanitarian Fund (UHF)': 'c7cxlv0m4s9ijd3jj',
      'Ukrainian Deminers Association (UDA)': 'c2gw1fem4s9ijd3jk',
      'Ukrainian Red Cross Society (URCS)': 'ciup47om4s9ijd3jl',
      "Ukrainian Women's Fund (UWF)": 'c5w6eqym4s9ijd3jm',
      'United Arab Emirates, Government of (United Arab Emirates)': 'coufgu3m4s9ijd3jn',
      'United Kingdom, Government of (United Kingdom)': 'crcupkqm4s9ijd3jo',
      'United Methodist Committee on Relief (UMCOR)': 'c808t79m4s9ijd3jp',
      "United Nations Children's Fund (UNICEF)": 'c5o64pvm4s9ijd3jq',
      'United Nations Development Programme (UNDP)': 'cm9v3nwm4s9ijd3jr',
      'United Nations High Commissioner for Refugees (UNHCR)': 'ccp7545m4s9ijd3js',
      'United Nations Population Fund (UNFPA)': 'c31yhmsm4s9ijd3ju',
      'United States Agency for International Development (USAID)': 'cphif85m4s9ijd3jv',
      'United States of America, Government of (United States of America)': 'cvysvx2m4s9ijd3jw',
      'Viet Nam, Government of (Viet Nam)': 'criuhwrm4s9ijd3jx',
      'Vodafone Portugal (Vodafone PT)': 'cpqr4glm4s9ijd3jy',
      'Volkshilfe Osterreich (Volkshilfe)': 'cjwaiw7m4s9ijd3jz',
      'White Cross Union (WhiteCross)': 'c6649qfm4s9ijd3k0',
      'World Bank (WB)': 'cbzgvium4s9ijd3k1',
      'World Childhood Foundation (WCF)': 'c2lv22bm4s9ijd3k2',
      'World Food Programme (WFP)': 'c6uvmptm4s9ijd3k3',
      'World Health Organization (WHO)': 'cnpyd95m4s9ijd3k4',
      'World Telehealth Initiative (WTI)': 'cgjhdr8m4s9ijd3k5',
      'World Vision International (WVI)': 'csrqf5dm4s9ijd3k6',
      'ZOA (ZOA)': 'c3shgksm4s9ijd3k7',
      '#stopsexting (#stopsexting)': 'cd8xuhm4s9ijd3k8',
      'EdCamp (EdCamp)': 'cpldfuam4s9ijd3k9',
      'Enlightening Initiative (EI)': 'ce1tmjm4s9ijd3ka',
      'Finn Church Aid (FCA)': 'cixbq9lm4s9ijd3kb',
      'La Strada-Ukraine (LaStradaUA)': 'c8fl8djm4s9ijd3kc',
      'Mondo (MONDO)': 'cs6ny7wm4s9ijd3kd',
      'Montessori UA (Montessori)': 'ct21rarm4s9ijd3ke',
      'Posmishka UA Charity Fund (Posmishka)': 'ct2ffjsm4s9ijd3kf',
      'Street Child (SC)': 'c3hgjclm4s9ijd3kg',
      'Teach - for Ukraine (Teach)': 'ca44tu8m4s9ijd3kh',
      'United Nations Educational, Scientific and Cultural Organization (UNESCO)': 'c7288xam4s9ijd3ki',
      'Direct Funding': 'c5ndoa9m4s9ijd3kj',
      'Novo Nordisk (NN)': 'ci51tvam4s9ijd3kk',
      'Howard G. Buffett Foundation (HBF)': 'c26kk99m4s9ijd3kl',
      "EU's Instrument contributing to Stability and Peace (IcSP)": 'chpip8cm4s9ijd3km',
      'East-SOS (East-SOS)': 'cibi2h1m4s9ijd3kn',
      'Fondation de France (FDF)': 'cay99arm4s9ijd3ko',
      'CARE International (CARE I)': 'c4p114nm4s9ijd3kp',
      'War Child (WCH)': 'cv7r9wbm4s9ijd4kq',
      'Angels of Salvation (AOS)': 'c8wjizkm4s9ijd4kr',
      'Service for Foreign Policy Instruments (FPI)': 'cjis370m4s9ijd4ks',
      'Peace and Stabilization Operations Program Canada (PSOPs)': 'cxi4d5sm4s9ijd4kt',
      'Scottland, Government of (Scottland)': 'cbwjgsbm4s9ijd4ku',
      'Pioneer (Pioneer)': 'cz50ppim4s9ijd4kv',
      'Viterra (Viterra)': 'cyi85h6m4s9ijd4kw',
      'Cargill  (Cargill)': 'cvw8zvgm4s9ijd4kx',
      'Association for Aid and Relief, Japan (AAR Japan)': 'cmt2wym4s9ijd4ky',
      'Plan International (PI)': 'caixrxim4s9ijd4kz',
      'GIRO 555 (GIRO555)': 'cx23jasm4s9ijd4l0',
      'Lumos Foundation (Lumos)': 'cuaj02pm4s9ijd4l1',
      'Fourfold Foundation (Fourfold)': 'c3nhlgzm4s9ijd4l2',
      'The Black Sea Trust for Regional Cooperation (BST)': 'cyu4uagm4s9ijd4l3',
      'Madrid City Council (Madrid CC)': 'csjjaerm4s9ijd4l4',
      'Necrosoft (Necrosoft)': 'ckrs02em4s9ijd4l5',
      'Verizon (Verizon)': 'civ20v9m4s9ijd4l6',
      'Voices of Children (VC)': 'c47pmr1m4s9ijd4l7',
      'United States Institute for Peace (USIP)': 'clgw7t1m4s9ijd4l8',
      'Ursula Zindel Hilti Foundation (UZH)': 'c3w14bzm4s9ijd4l9',
      'Mines Advisory Group International (MAG)': 'cvhmadvm4s9ijd4la',
      'Tetra Tech (TetraTech)': 'csh17gcm4s9ijd4lb',
      'EU Directorate General for International Partnerships (INTPA)': 'cgfu50xm4s9ijd4lc',
      'Embassy of the Netherlands (NLEmbassy)': 'chpioepm4s9ijd6ld',
      'The Foundation by Dr. Friedrich Vogel-Stiftung (Vogel)': 'cnx7df5m4s9ijd6le',
      'Danish Red Cross (DRK)': 'cqxpqsym4s9ijd6lf',
      'Liechtenstein, Government of (Liechtenstein)': 'cthewpom4s9ijd6lg',
      'Ministry of Foreign Affairs of the Republic of Korea (MFA Korea)': 'c33e844m4s9ijd6lh',
      'Ministry of Justice - Sweden (MJ Sweden)': 'cnmzhynm4s9ijd6li',
      "U.S. Department of State's Office to Monitor and Combat Trafficking in Persons (TIP)": 'cb2oppqm4s9ijd7lj',
      'USAID Mission to Ukraine (USAID Ukraine)': 'c85fqabm4s9ijd7lk',
      'ActionAid International (AAI)': 'csrz9cym4s9ijd7ll',
      'Saxon State Parliament (SSP)': 'cvfx40ym4s9ijd7lm',
      'Caritas Korea (Caritas Korea)': 'c1yywy7m4s9ijd7ln',
      'Caritas Spain (Caritas Spain)': 'c8fd3lnm4s9ijd7lo',
      'Australian Federation of Ukrainian Organisations (AFUO)': 'ckt632rm4s9ijd7lp',
      'Kindermissionswerk Die Sternsinger (Sternsinger)': 'c1tm79qm4s9ijd7lq',
      'Razom (RZ)': 'c9mdvljm4s9ijd7lr',
      'United Nations Office on Drugs and Crime (UNODC)': 'c4zqmtam4s9ijd7ls',
      'Nachbar in Not (NIN)': 'cit3gnxm4s9ijd7lt',
      'Danmarks Indsamling (DI)': 'ch8lymhm4s9ijd7lu',
      'Spanish Agency for International Development Cooperation (AECID)': 'cm7fpixm4s9ijd7lv',
      'Cordaid (Cordaid)': 'cks3nckm4s9ijd7lw',
      '100% Life Rivne (100%Life Rivne)': 'cg1cxfgm4s9ijd7lx',
      'Caritas France (Caritas France)': 'cmjts9pm4s9ijd7ly',
      'Google.org (Google.org)': 'cnypiunm4s9ijd7lz',
      'Office of the United Nations High Commissioner for Human Rights (OHCHR)': 'c539od5m4s9ijd7m0',
      'Terre des Hommes (TDH)': 'cqbcbkcm4s9ijd7m1',
      'Croatia, Government of the Republic of (Croatia)': 'cghbscym4s9ijd7m2',
      'Augustinus Foundation (Augustinus)': 'ckwobwmm4s9ijd7m3',
      'Ministry of Foreign Affairs of the Republic of China (Taiwan) (MFA China)': 'cncsfnbm4s9ijd7m4',
      'Netherlands Helsinki Committee (NHC)': 'c31uow9m4s9ijd7m5',
      'Global Partnership for Education (GPE)': 'cy7nzfgm4s9ijd7m6',
      'Food and Agriculture Organization (FAO)': 'cycbu39m4s9ijd7m7',
      'World Vision Australia (WVA)': 'cqfm7t4m4s9ijd7m8',
      "Support to Ukraine's Reforms for Governance Project (SURGe)": 'ck1ctxqm4s9ijd7m9',
      'Libereco (Libereco)': 'ckl3km8m4s9ijd7ma',
      'Austrian Development Agency (ADA)': 'cuvc6grm4s9ijd7mb',
      'Think Equal (TE)': 'c2cnx6wm4s9ijd7mc',
      "Women's Peace & Humanitarian Fund (WPHF)": 'co7wo2xm4s9ijd7md',
      'Resource Center of Non-Governmental Organizations (NGORC)': 'cvvodojm4s9ijd7me',
      'Polish Humanitarian Action (PAH)': 'cal94fjm4s9ijd7mf',
      'Initiative Center to Support Social Action Ednannia (Ednannia)': 'c9b4hlrm4s9ijd7mg',
      'US Embassy in Ukraine (US Embassy)': 'czeeuu6m4s9ijd7mh',
      'Consortium 12-12 (1212)': 'ck56wjqm4s9ijd7mi',
      'FMC Corporation (FMC)': 'cm4mdwqm4s9ijd7mj',
      'International Centre for Migration Policy Development (ICMPD)': 'c2htlqum4s9ijd7mk',
      'Ukrainian Education Platform (UEP)': 'c6baluem4s9ijd7ml',
      'Regione Emilia Romagna (RER)': 'cgv8jptm4s9ijd7mm',
      'Gilead Sciences (Gilead)': 'c8ypaxwm4s9ijd8mn',
      'World Jewish Relief (WJR)': 'cl04g7jm4s9ijd8mo',
      'Veterinarians Without Borders / Veterinaires sans frontieres - Canada (VWB/VSF Canada)': 'ceq64fvm4s9ijd8mp',
      'Alinea International (Alinea)': 'cac9tolm4s9ijd8mq',
      'Kvinna till Kvinna Foundation (Kvinna)': 'ced3h73m4s9ijd8mr',
      'Postcode Ukraine (Postcode)': 'co8iqt4m4s9ijd8ms',
      'Danish Support Group Ukraine (DSGU)': 'cr5c89qm4s9ijd8mt',
      'City of Power (CoP)': 'c83l1hdm4s9ijd8mu',
      'Lombardia Region, Italy (Lombardia)': 'c58tsevm4s9ijd8mv',
      'ActionAid Italy (AAIT)': 'c7ilgndm4s9ijd8mw',
      'Center for Disaster Philanthropy (CDP)': 'crumre4m4s9ijd8mx',
      'Spirit of America (SOA)': 'c15epc1m4s9ijd8my',
      'Xunta de Galicia (Spain) (XuntaSpain)': 'c9861vdm4s9ijd8mz',
      'East Europe Foundation (EEF)': 'cbbo2kmm4s9ijd8n0',
      'ITF Enhancing Human Security (ITF)': 'ci9o6n4m4s9ijd8n1',
      'Knights of Columbus (KOFC)': 'cgkn6qbm4s9ijd8n2',
      'Chemonics International (Chemonics)': 'cnd3tzjm4s9ijd8n3',
      'World of Future (WF)': 'cejjoy0m4s9ijd8n4',
      'United Nations Joint Program on AIDS (UNAIDS)': 'cawkq2zm4s9ijd8n5',
      'BlueCheck (BlueCheck)': 'carpe5em4s9ijd8n6',
      'Deloitte (Deloitte)': 'ce7l0bwm4s9ijd8n7',
      'Concern Worldwide (CWW)': 'ciswrmom4s9ijd8n8',
      'Help - Hilfe zur Selbsthilfe e.V. (HELP e.V.)': 'cgjyvflm4s9ijd8n9',
      'KfW Development Bank (KfW)': 'cda2llbm4s9ijd8na',
      'Norwegian Agency for Development Cooperation (Norad)': 'cjgm71um4s9ijd8nb',
      'ELIS (ELIS)': 'cpwqymm4s9ijd8nc',
      'Diakonie Katastrophenhilfe (DK)': 'c6zcfigm4s9ijd8nd',
      'Action Against Hunger (AAH)': 'cpqbcrzm4s9ijd8ne',
      'Charles Stewart Mott Foundation (Mott)': 'cq1b322m4s9ijd8nf',
      'Multiple Donors (MDonors)': 'cw5t20mm4s9ijd8ng',
      'Beisheim Stiftung (Beisheim)': 'ceqk7b4m4s9ijd8nh',
      'OutcomesX (OutcomesX)': 'c4w8nikm4s9ijd8ni',
      'Optima Education Center (Optima)': 'cq8ct9dm4s9ijd8nj',
      'Caritas Slovenia (CaritasSVN)': 'cdyum2nm4s9ijd8nk',
      'Caritas Ukraine (CaritasUA)': 'c71tscqm4s9ijd8nl',
      'Catholic Near East Welfare Association Canada (CNEWA Canada)': 'ci1mjyfm4s9ijd8nm',
      'GURT Resource Centre (GURT)': 'cur943cm4s9ijd8nn',
      'Fund for Social Protection of Persons with Disabilities (FSPPWD)': 'c4uebtzm4s9ijd8no',
      'Global Network of People Living with HIV (GNP+)': 'cgzkq8cm4s9ijd8np',
      'Oxfam Great Britain (Oxfam GB)': 'csjsxsrm4s9ijyqnq',
      'Ukraine, Government of (Ukraine)': 'c3j21oem4s9ijyqnr',
      'MedGlobal (MG)': 'cwnfwvlm4s9ijyqns',
      'Department of Social Policy of Cherkasy City Council (DSPCHCC)': 'cr7nv5vm4s9ijyqnt',
      'Great Commission Society (GCS)': 'comuczbm4s9ijyqnu',
      'Ukrainian Catholic Education Foundation (UCEF)': 'cqyqujhm4s9ijyqnv',
      'Presbyterian Church (USA) (PC USA)': 'cdik8i4m4s9ijyqnw',
      'The Ministry of Education and Research of Sweden (MERS)': 'c2zgbllm4s9ijyqnx',
      'H&M Group (H&M)': 'c9o86igm4s9ijyqny',
      'Mercedes-Benz US International (Mercedes)': 'clc3itmm4s9ijyqnz',
      'Kindernothilfe (Kindernothilfe)': 'c5qy2kvm4s9ijyqo0',
      'Mondelez International Foundation (Mondelez IF)': 'cmwtbkam4s9ijyqo1',
      'PepsiCo Foundation (PepsiCo)': 'csha4trm4s9ijyqo2',
      'Catholic Agency for Overseas Development (CAFOD)': 'ckh981m4s9ijyqo3',
      'Adventist Development and Relief Agency Deutschland e.V. (ADRA Deutschland)': 'ctb0pqfm4s9ijyqo4',
      'GoodWill (GoodWill)': 'c4wdwstm4s9ijyqo5',
      'Office of Perspective Development (OPR)': 'c4fv5am4s9ijyqo6',
      'Ensemble Ukraine (EUK)': 'cba9v7sm4s9ijyqo7',
      'Be a Hero for Ukraine (BAHFU)': 'c6xtdkwm4s9ijyqo8',
      'Renovabis (Renovabis)': 'cn3fpglm4s9ijyqo9',
      'Unity and Strength (U&S)': 'c3qwlumm4s9ijyqoa',
      'Private Donor (PDonor)': 'c812k8mm4s9ijyqob',
      'Trocaire (Trocaire)': 'cfdwkrsm4s9ijyqoc',
      'SlovakAid (SlovakAid)': 'chctzawm4s9ijyqod',
      'Medico International (Medico)': 'cy2fdrnm4s9ijyqoe',
      'Catholic Medical Mission Board (CMMB)': 'cbvl672m4s9ijyqof',
      'Friends of Chervonohrad (FC)': 'c7t0nq9m4s9ijyqog',
      'District #1 (District#1)': 'c31o4dnm4s9ijyqoh',
      'Nova Ukraine (NovaUA)': 'cq8flpim4s9ijyqoi',
      'Outright International (Outright)': 'c52f1fem4s9ijyqoj',
      'Deutsch-Ukrainisches Forum e.V. (DUF)': 'cpgu3uqm4s9ijyqok',
      'Lutheran World Federation (LWF)': 'cyi058bm4s9ijyqol',
      'TERRA TECH (TERRATECH)': 'caax89km4s9ijyqom',
      'OLAM (OLAM)': 'cm4e3ocm4s9ijyqon',
      'Farmaceuticos Mundi (Farmamundi)': 'cf29j6qm4s9ijyqoo',
      'Ukrainian National Women’s League of America (UNWLA)': 'cg033s2m4s9ijyqop',
      'If! Foundation (If!)': 'ctb15qjm4s9ijyqoq',
      'Hilfswerk International (HWI)': 'ckieh1ym4s9ijyqor',
      'The German Marshall Fund of the United States (GMF)': 'csmsiedm4s9ijyqos',
      'Ukrainian Soul (UkrSoul)': 'cw2397am4s9ijyqot',
      'Adventist Development and Relief Agency Japan (ADRA Japan)': 'ctjpybvm4s9ijyqou',
      'Ukrainian Feminist Network for Freedom and Democracy (Femnet)': 'cy9mrvsm4s9ijyqov',
      'Global Communities (GC)': 'ce2dw9am4s9ijyqow',
      'Mennonite Central Committee Ukraine (MCCUA)': 'cnp260vm4s9ijyqox',
      'Aktion Mensch (AktionMensch)': 'crth65im4s9ijyqoy',
      'Diaconia of the Evangelical Church of Czech Brethren – Center of Relief and Development (Diaconia ECCB – CRD)':
        'ctpydj0m4s9ijyqoz',
      'Representative Office of the German Adult Education Association (DVVInternational)': 'ca378sbm4s9ijyqp0',
      'The Tree of Life - Ukraine (TOL-UA)': 'cgvjbe9m4s9ijyqp1',
      'Alight (ALIGHT)': 'cc2lkudm4s9ijyqp2',
      'Diakonie ACT Austria (DAA)': 'c7nkyb2m4s9ijyrp3',
      'Evangelical Lutheran Church in America (ELCA)': 'cvp6ro9m4s9ijyrp4',
      'Faroe Islands Ministry of Justice (FIMJ)': 'clsyy63m4s9ijyrp5',
      'Nasha Sprava Ukraina (NSU)': 'ccw31grm4s9ijyrp6',
      'Korea International Cooperation Agency (KOICA)': 'c1qw1frm4s9ijyrp7',
      'Australian Department of Home Affairs (AUGov)': 'cxb2i8nm4s9ijyrp8',
      'Australian Embassy in Ukraine (AUEmbassy)': 'c2pc0b9m4s9ijyrp9',
      'Ukraine Community Recovery Fund (UCRF)': 'cm6qm01m6jfa86x2',
      'Vestland County Council (VestlandCC)': 'crbsmpbm6jfh0a9x1v',
      'Church World Service (CWS)': 'cc4hrlcm6jfh0a9x1w',
      'NEEKA (NEEKA)': 'c4pktogm6jfh0a9x1x',
      'Taiwan International Cooperation and Development Fund (TaiwanICDF)': 'cg5z6tmm6uhjenc5',
      "L'Albero della Vita (FADV)": 'cryvl1lm6yueoon2',
      'Caritas Sweden (CaritasSE)': 'cc4hyjxm7akee3v2',
      'ERIKS Development Partner (ERIKS)': 'cdtzqwhm7erta1w2',
      'HelpDesk Media (HelpDesk)': 'cbufcqdm7erta1x3',
      'Janz Foundation (Janz)': 'cty66bmm7erta1x4',
      'Myriad Canada (MyriadCa)': 'ca096b5m7erta1x5',
      'Nehemia Team (NehemiaTeam)': 'cemi7um7erta1x6',
      'Serving Orphans Worldwide (SOW)': 'cep9pfum7erta1x7',
      'Stirling Foundation (Stirling)': 'c93pf1em7erta1x8',
      'Adventist Development and Relief Agency Czech Republic (ADRA Czech Republic)': 'cy0ayxjm7nfojbs2',
      "Barbara Sinatra Children's Center (BSinatraCC)": 'cmz3z2gm7njmnpk2',
      'Team4UA (T4UA)': 'cxwvdbom7njmnpk3',
      'RadioAid (RadioAid)': 'cdfnzxvm7njsyi14',
      'Solidar Suisse (SSW)': 'cgfzh5om7ojd7rp2',
      'GlobalGiving (GlobalGiving)': 'cygtjxom7ssvket3',
      'Archeparchy of Philadelphia (UkrCatholic)': 'ccqt000m7ukhvdl2',
      'Jewish Federations of North America (JFNA)': 'c4w1j3rm7ukhvdl3',
      'United Jewish Appeal - Federation of New York (UJA)': 'c1fpez6m7ukhvdl4',
    },
    'Indicators - WASH': {
      'Water & waste-water systems emergency support (i.e., support to Vodakanals) > # of individuals benefiting from the provision of machinery/equipment':
        'ccrhtfnm6ukn8yu2',
      'Water & waste-water systems emergency support (i.e., support to Vodakanals) > # of individuals benefiting from the provision of generators for water/wastewater service providers':
        'c4ouoyzm6ukn8yv3',
      'Water & waste-water systems emergency support (i.e., support to Vodakanals) > # of individuals benefiting from the provision of water treatment supplies (Chlorine, coagulants, etc.)':
        'ca5qivwm6ukn8yv4',
      'Water & waste-water systems emergency support (i.e., support to Vodakanals) > # of individuals benefiting from the provision of leak detection equipment/training':
        'clsv4ahm6ukn8yv5',
      'Water & waste-water systems emergency support (i.e., support to Vodakanals) > # of individuals benefiting from the provision of water testing materials/equipment':
        'chb7pemm6ukn8yv6',
      'Water & waste-water systems emergency support (i.e., support to Vodakanals) > # of individuals benefiting from the provision of PPE/safety equipment':
        'choxwodm6ukn8yv7',
      'Emergency water supply > # of individuals benefiting from the new water source construction or rehabilitation (boreholes, wells, etc.)':
        'cbba80bm6ukn8yv8',
      'Emergency water supply > # of individuals benefiting from the distribution of household water treatment materials':
        'c65wze9m6ukn8yv9',
      'Emergency water supply > # of individuals benefiting from the installation / operation of water treatment units and temporary distribution systems':
        'c2ehkyim6ukn8yva',
      'Emergency water supply > # of individuals benefiting from the provision of bottled water / distribution of water bottles':
        'ceuhdwwm6ukn8yvb',
      'Emergency water supply > # of individuals benefiting from the provision of water trucking': 'c9clyhjm6ukn8yvc',
      'Emergency water supply > # of individuals benefiting from the provision / installation of water storage tanks':
        'cuynl4xm6ukn8yvd',
      'Emergency water supply > # of individuals benefiting from the provision of jerry cans for household water storage':
        'clierz5m6ukn8yve',
      'WASH NFI distributions (cash or voucher) > # of individuals benefiting from hygiene kit/items distribution (cash or voucher)':
        'cyk923lm6ukn8yvf',
      'WASH NFI distributions (in-kind) > # of individuals benefiting from hygiene kit/items distribution (in-kind)':
        'cfklmzwm6ukn8yvg',
      'WASH NFI distributions (in-kind) > # of individuals benefiting from hygiene promotion activities':
        'cjbn70om6ukn8yvh',
      'Water & waste-water systems Operation & Maintenance (O&M) and rehabilitation (i.e., support to Vodakanals) > # of individuals benefiting from the repair of existing centralized water system':
        'cevudbom6ukn8yvi',
      'Water & waste-water systems Operation & Maintenance (O&M) and rehabilitation (i.e., support to Vodakanals) > # of individuals benefiting from the rehabilitation of off-site sewage treatment, pumping stations or sewage networks':
        'cwr4z3tm6ukn8yvj',
      'Water & waste-water systems Operation & Maintenance (O&M) and rehabilitation (i.e., support to Vodakanals) > # of individuals benefiting from the repair of existing decentralized water systems (boreholes, wells, etc.) (operated by service providers only)':
        'czg44umm6ukn8yvk',
      'Water & waste-water systems Operation & Maintenance (O&M) and rehabilitation (i.e., support to Vodakanals) > # of individuals trained':
        'c2ppbc6m6ukn8yvl',
      'District Heating systems repairs and rehabilitation > # of individuals assisted through the repairs/rehabilitation/improvment of centralized heating systems':
        'crm6l8jm6ukn8yvm',
      'District Heating systems repairs and rehabilitation > # of individuals assisted through the provision of equipment/materials for centralized heating systems':
        'c4pd2inm6ukn8yvn',
      'District Heating systems repairs and rehabilitation > # of individuals assisted through the supply of modular boiler houses for centralized heating systems':
        'c8kots3m6ukn8yvo',
      'District Heating systems repairs and rehabilitation > # of individuals assisted through the provision of co-generation units for heating systems':
        'c8k3lcmm6ukn8yvp',
      'District Heating systems repairs and rehabilitation > # of individuals assisted through the provision of generators for heating systems':
        'cg9xsnem6ukn8yvq',
      'WASH interventions in institutions (i.e. schools, hospitals, and collective centers) > # of individuals benefiting from the sustainable connection or rehabilitation of water networks in facilities (incl. boreholes, water treatment equipment etc.)':
        'conu2yxm6ukn8yvr',
      'WASH interventions in institutions (i.e. schools, hospitals, and collective centers) > # of individuals benefitting from rehabilitation/installation of adequate sanitation facilities (e.g., toilets, showers & hot water boilers, wastewater, etc.)':
        'csblj2pm6ukn8yvs',
      'WASH interventions in institutions (i.e. schools, hospitals, and collective centers) > # of individuals benefiting from provision of laundry equipment (dryers, washing machines)':
        'cunopm1m6ukn8yvt',
      'WASH interventions in institutions (i.e. schools, hospitals, and collective centers) > # of individuals benefiting from the provision of institutional cleaning kits for environmental cleaning and/or infection prevention and control services':
        'clif0aym6ukn8yvu',
      'WASH interventions in institutions (i.e. schools, hospitals, and collective centers) > # of individuals benefiting from the provision/construction of handwashing stations at the required locations (e.g., sanitation facilities, all points of medical care, facility entrance, etc.)':
        'cvb7pf5m6ukn8yvv',
      'WASH interventions in institutions (i.e. schools, hospitals, and collective centers) > # of individuals benefitting from access to safely managed solid and health care waste including segration and processing of waste (e.g. incineration, burial, etc.)':
        'ce8tqlzm6ukn8yvw',
      'WASH interventions in institutions (i.e. schools, hospitals, and collective centers) > # of individuals benefitting from training in IPC, (menstrual) hygiene promotion, WASH FIT, and related areas for improved facility management':
        'c8e5rnnm6ukn8yvx',
      'Solid waste management support and repairs > # of individuals assisted through the provision of solid waste management materials / consumables (bins, bags, etc.)':
        'ccnfx5sm6ukn8yvy',
      'Solid waste management support and repairs > # of individuals assisted through support to solid waste collection / disposal services':
        'cgjkaoym6ukn8yvz',
    },
    'Population Group': {'Internally Displaced': 'c3yfomom4s6zizi20', 'Non-Displaced': 'cjccin8m4s6ztsm21'},
    'Outside HNRP Scope categories': {
      'Outside priority areas': 'c3ap6l0m4vgd4ov4',
      'Funding not reported in FTS​': 'c9801rnm4vgdewn5',
      'Delivered outside HNRP​ mechanism': 'cgc12ggm4vgdovj6',
      'Not aligned to guidance': 'cei6bscm4vgdvpq7',
    },
    Theme: {'No specific theme': 'chfni9m6ao2j8b8'},
    'Type of institution / Beneficiary': {
      'Individuals/households': 'cvdho9fm6aof1chf',
      Vodocanal: 'cj2bscdm6aog8l9h',
      'Collective centers for IDPs': 'cm1roknm6aogdnfi',
      'Health Institution': 'cfk16d3m6aogjvzj',
      'Education Institution': 'cgs508m6aogq43k',
      'Social Institution': 'c5ki74dm6aogvltl',
      'District Heating': 'cbe26vlm6aoh0sam',
      'Local authority': 'c2p1p2fm6aoh5v6n',
      'Other Institution': 'cl2ptykm6aohbjro',
    },
    'Is the disaggregation by population group, gender and age known?': {
      Yes: 'cylxocm6aqfz58v',
      No: 'c1650k5m6aqj6zyx',
    },
    'HNRP Scope': {'Outside HNRP Scope': 'ckjb30sm6f3aa9u3'},
  }
}
