export type DrcUaStaffs = {
  fullName: string
  email: string
  job: string
  nameOrg: string
}

export const drcUaStaffs: DrcUaStaffs[] = [
  {
    fullName: 'Ольга Левченко',
    email: 'olmyshanych@gmail.com',
    job: 'Communications Manager',
    nameOrg: 'БО "Діалог громад"',
  },
  {
    fullName: 'Руслан Івах',
    email: 'admin@pomogaem.com.ua',
    job: 'IT specialist',
    nameOrg: 'БО "Діалог громад"',
  },
  {
    fullName: 'Марія Бойко',
    email: 'tvd@care-in-action.org',
    job: 'Director',
    nameOrg: 'PO "Turbota v Dii"',
  },
  {
    fullName: 'Оксана Міщенко',
    email: 'mischenko@care-in-action.org',
    job: 'Social Worker',
    nameOrg: 'PO "Turbota v Dii"',
  },
  {
    fullName: 'Олена Сьомкіна',
    email: 'Somkina@care-ib-action.org',
    job: 'Operations Manager',
    nameOrg: 'PO "Turbota v Dii"',
  },
  {
    fullName: 'Петрова Каріна',
    email: 'petrovakarina637@gmail.com',
    job: ' Social Work Specialist',
    nameOrg: 'PO "Turbota v Dii"',
  },
  {
    fullName: 'Венгер Віталій',
    email: 'Venger@care-in-action.org',
    job: 'Driver',
    nameOrg: 'PO "Turbota v Dii"',
  },
  {
    fullName: 'Катерина Шкуратівська',
    email: 'kateryna.shkurativska@gmail.com',
    job: 'Education Project Manager',
    nameOrg: 'СF "Blagomay"',
  },
  {
    fullName: 'Катерина Вишня',
    email: 'kateryna.vyshnia@charitymay.com',
    job: 'Executive Assistant',
    nameOrg: 'СF "Blagomay"',
  },
  {
    fullName: 'Маргарита Доброштан',
    email: 'marharyta.dobroshtan@charitymay.com',
    job: 'MEAL Manager',
    nameOrg: 'СF "Blagomay"',
  },
  {
    fullName: 'Анастасія Жабка',
    email: 'zhabkva@gmail.com',
    job: 'Coordinator for a Vocational Training',
    nameOrg: 'Feminist Workshop',
  },
  {
    fullName: 'Панченко Ганна',
    email: 'media@femwork.org',
    job: 'Media Coordinator',
    nameOrg: 'NGO "Feminist Workshop"',
  },
  {
    fullName: 'Довбня Катерина',
    email: 'crisis@femwork.org',
    job: 'Program Area Coordinator',
    nameOrg: 'NGO "Feminist Workshop"',
  },
  {
    fullName: 'Степан Деркунський',
    email: 'derkunskiysv@gmail.com',
    job: '',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Євген Врогуля',
    email: 'xisus.ven82@gmail.com',
    job: 'Distribution Specialist',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Інна Брушко',
    email: 'I.brushko@mistosyly.org',
    job: 'Referral Specialist',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Роман Куропятник',
    email: 'roman_kuropiatnyk@pomogaem.com.ua',
    job: 'Project Manager',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Тетяна Грисенко',
    email: 'buh@pomogaem.com.ua',
    job: 'Accountant',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Олена Єкатериніна',
    email: 'yekaterynina@pomogaem.com.ua',
    job: 'Procurement Specialist',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Олена Друшляк',
    email: 'lena@pomogaem.com.ua',
    job: 'MEAL Specialist',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Олексій Журавель',
    email: 'oleksii@pomogaem.com.ua',
    job: 'AAP Specialist',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Анна Доставалова',
    email: 'annamihey491@gmail.com',
    job: 'Mobile Team Coordinator',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Діана Косьян',
    email: 'dianakasyanxxx@gmail.com',
    job: 'Field Coordinator',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Васильцова Аліна Олександрівна',
    email: 'avasyltsova@charity-aos.com',
    job: 'Project manager',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Холмецька Олена Дмитрівна',
    email: 'okholmetska@charity-aos.com',
    job: 'Assistant project manager',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Олексієнко Михайло Дмитрович',
    email: 'moleksiienko@charity-aos.com',
    job: 'Date base specialist',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Оленченко Олександр Сергійович',
    email: 'oolenchenko@charity-aos.com',
    job: 'MEAL Manager',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Кузнєцова Ольга Леонідівна',
    email: 'avasyltsova@charity-aos.com',
    job: 'Hotline and post monitoring',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Афанасьєва Олена Андріївна',
    email: 'eafanasieva@charity-aos.com',
    job: 'Cluster manager',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Панченко Артем Дмитрович',
    email: 'apanchenko@charity-aos.com',
    job: 'Photographer',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Усенко Таїсія Ігорівна',
    email: 'tusenko@charity-aos.com',
    job: 'Communications Manager',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Валевська Станіслава Станіславівна',
    email: 'svalevska@charity-aos.com',
    job: 'Psychologist',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Кайдаш Лариса Володимирівна',
    email: 'kaidash@charity-aos.com',
    job: 'Accountant',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Сидоренко Інна Василівна',
    email: 'isydorenko@charity-aos.com',
    job: 'Specialist in the collection of financial statements',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Супрун Павло Сергійович',
    email: 'psuprun@charity-aos.com',
    job: 'Security specialist',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Петрушова Анастасія Олександрівна',
    email: 'apetrushova@charity-aos.com',
    job: 'Tender procurement specialist',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Донцов Дмитро Георгійович',
    email: 'avasyltsova@charity-aos.com',
    job: 'Registrar',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Стародубець Наталя',
    email: 'bery_i_slav@ukr.net',
    job: 'Coordinator',
    nameOrg: 'PO "Bery i Slav"',
  },
  {
    fullName: 'Уварова Анастасія Сергіївна',
    email: 'admin@vpo.lviv.ua',
    job: 'Art Therapist',
    nameOrg: 'PO "Bery i Slav"',
  },
  {
    fullName: 'Юлія Шандра',
    email: 'avangart07@ukr.net',
    job: 'Communications Manager',
    nameOrg: 'PO "Bery i Slav"',
  },
  {
    fullName: 'Сергій Стародубець',
    email: 'star_sl@ukr.net',
    job: 'Coordinator',
    nameOrg: 'PO "Bery i Slav"',
  },
  {
    fullName: 'Vadym Statsenko',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Civic organization "THE TENTH OF APRIL"',
  },
  {
    fullName: 'Andrii Ivanov',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Civic organization "THE TENTH OF APRIL"',
  },
  {
    fullName: 'Iryna Savchenko',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Civic organization "THE TENTH OF APRIL"',
  },
  {
    fullName: 'Пащенко Олександр',
    email: '',
    job: 'Coordinator',
    nameOrg: 'Civic organization "THE TENTH OF APRIL"',
  },
  {
    fullName: 'Олена Дейнега',
    email: 'olenad55kherson@gmail.com',
    job: 'Finance Manager',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Яна Богомолова',
    email: 'bogomolovayana1304@gmail.com',
    job: 'Accountant',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Канцідал Наталія',
    email: '',
    job: 'Lawyer',
    nameOrg: 'БО "Діалог громад"',
  },
  {
    fullName: 'Олександр Коваленко',
    email: '',
    job: 'Lawyer',
    nameOrg: 'БО "Діалог громад"',
  },
  {
    fullName: 'Олександр Магдаліц',
    email: '',
    job: 'Coordinator',
    nameOrg: 'БО "Діалог громад"',
  },
  {
    fullName: 'Андрій Єлісєєв',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Caritable organization "Caritable Foundation "Caritas Kharkiv"',
  },
  {
    fullName: 'Золотухіна Ілона',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Caritable organization "Caritable Foundation "Caritas Kharkiv"',
  },
  {
    fullName: 'Ірина Козаченко',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Caritable organization "Caritable Foundation "Caritas Kharkiv"',
  },
  {
    fullName: 'Кунець Сергій',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Caritable organization "Caritable Foundation "Caritas Kharkiv"',
  },
  {
    fullName: 'Гудзенко Юлія',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Caritable organization "Caritable Foundation "Caritas Kharkiv"',
  },
  {
    fullName: 'Штика Світлана',
    email: '',
    job: 'Case Manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Вікторія Гриценко',
    email: '',
    job: 'Communications Manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Мошенська Катерина Олександрівна',
    email: 'avasyltsova@charity-aos.com',
    job: 'Registrar',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Пономарева Тетяна Валентинівна',
    email: 'avasyltsova@charity-aos.com',
    job: 'Queue controller',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: "Зеньо Мар'яна",
    email: 'Grinyuk0910@gmail.com',
    job: 'Accountant',
    nameOrg: 'PO "Bery i Slav"',
  },
  {
    fullName: 'Аліна Гніденко',
    email: '',
    job: 'Psychologist',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Холоша Марія',
    email: '',
    job: 'Psychologist',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Людмила Пономаренко',
    email: '',
    job: 'Coordinator',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Агєнтаєв Олексій',
    email: '',
    job: 'Coordinator',
    nameOrg: 'Non-Governmental Organization "Strategies and Technologies for Effective Partnership ("STEP")"',
  },
  {
    fullName: 'Марія Череп',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization "Strategies and Technologies for Effective Partnership ("STEP")"',
  },
  {
    fullName: 'Андрій Александрович',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization "Strategies and Technologies for Effective Partnership ("STEP")"',
  },
  {
    fullName: 'Антон Стасік',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization "Strategies and Technologies for Effective Partnership ("STEP")"',
  },
  {
    fullName: 'Семеренко Сергій',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization "Strategies and Technologies for Effective Partnership ("STEP")"',
  },
  {
    fullName: 'Бабенко Ганна',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization "Strategies and Technologies for Effective Partnership ("STEP")"',
  },
  {
    fullName: 'Учкін Даніл',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization "Strategies and Technologies for Effective Partnership ("STEP")"',
  },
  {
    fullName: 'Димитрієв Дмитро',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization "Strategies and Technologies for Effective Partnership ("STEP")"',
  },
  {
    fullName: 'Oleksandr Peftibai',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Caritable Organization "Parish Caritable Foundation "Caritas Mariupol"',
  },
  {
    fullName: 'Oksana Fedorova',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Caritable Organization "Parish Caritable Foundation "Caritas Mariupol"',
  },
  {
    fullName: 'Kramarenko Svitlana',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Caritable Organization "Parish Caritable Foundation "Caritas Mariupol"',
  },
  {
    fullName: 'Євген Гілін',
    email: 'i_gilin@mistosyly.org',
    job: 'Head',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Ольга Палагнюк',
    email: 'olenkasp2608@gmail.com',
    job: 'Radio Operator',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Марія Деркунська',
    email: 'mariyadaniela30@gmail.com',
    job: 'Distribution Officer',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Олена Ковальчук',
    email: 'kovalchukelena602@gmail.com',
    job: 'Distribution Officer',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Максим Глібов',
    email: 'max2401.86@ukr.net',
    job: 'Distribution Officer',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Вікторія Борискіна',
    email: 'v.boriskina@mistosyly.org',
    job: 'MEAL Specialist',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Микола Шаповал',
    email: 'mykola.shapoval@gmail.com',
    job: 'Project Assistant ',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Науменко Дмтиро',
    email: '',
    job: 'Coordinator',
    nameOrg: 'Non-Governmental Organization “MART”',
  },
  {
    fullName: 'Барабаш Роман',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization “MART”',
  },
  {
    fullName: 'Жилінський Олександр',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization “MART”',
  },
  {
    fullName: 'Мохир Дмтиро',
    email: '',
    job: 'Lawyer',
    nameOrg: 'Non-Governmental Organization “MART”',
  },
  {
    fullName: 'Марина Кісліцина',
    email: 'marinakislitsyna05@gmail.com',
    job: 'Support Group Facilitator',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Шимчук Ірина',
    email: 'Irinasmck@gmail.com',
    job: 'Case Manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Інна Мороз',
    email: 'pavluchenko822@gmail.comp',
    job: 'Case Manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Альона Мирошниченко',
    email: '0661468678@ukr.net',
    job: 'Facilitator',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Людмила Пономаренко',
    email: 'p_li@ukr.net',
    job: 'Project manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Петро Сухоставець',
    email: 'petr_s@ukr.net',
    job: 'Financial Manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Анна Крамар',
    email: 'anuta__m@ukr.net',
    job: 'MEAL manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Ольга Хоружа',
    email: 'olga.masalitova@gmail.com',
    job: 'Trainer',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Аліна Гніденко',
    email: 'gordienko.92@ukr.net',
    job: 'Psychologist',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Anastasiia Kolchyk',
    email: 'nastyakolchik@yahoo.com',
    job: 'Interpreter',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Віталія Лашхі',
    email: 'vitaliyalashhi@gmail.com',
    job: 'Project Administrator',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Оксана Беспалова',
    email: 'i-ozon777@i.ua',
    job: 'Psycho-gymnastics Trainer',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Вікторія Гриценко',
    email: 'viktoriia.gr16@gmail.com',
    job: 'Communications Manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Яна Білокур',
    email: 'janabilokur118@gmail.com',
    job: 'Art Therapy Trainer',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Діна Рішка',
    email: 'rds2017@ukr.net',
    job: 'Lawyer',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Лариса Дворніченко',
    email: 'laradvornichenko@gmail.com',
    job: 'Psychologist',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Тетяна Бортник',
    email: 'tat-bortnik@ukr.net',
    job: 'Case Manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Larysa Chekanska',
    email: 'chaikachekanska@gmail.com',
    job: 'Psychologist',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Аліна Гніденко',
    email: 'gordienko.92@ukr.net',
    job: 'Psychologist',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Володимир Непран',
    email: 'volodimir_nepran@pomogaem.com.ua',
    job: 'Driver',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Аліфіренко Антон',
    email: 'a.alifirenko@lampa.ngo',
    job: 'Executive Director',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Кононенко Алла',
    email: 'a.kononenko@lampa.ngo',
    job: 'Program manager',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Єрмоленко Ірина',
    email: 'i.ermolenko@lampa.ngo',
    job: 'Communications Manager',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Мося Денис',
    email: 'd.mosya@lampa.ngo',
    job: 'MEAL Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Козянко Катерина',
    email: 'k.kozianko@lampa.ngo',
    job: 'CFM Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Булденко Олександр',
    email: 'o.buldenko@lampa.ngo',
    job: 'Procurement Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Зацарина Анастасія',
    email: 'a.zatsarynna@lampa.ngo',
    job: 'Finance Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Щербакова Ганна',
    email: 'annashcerbakova86@gmail.com',
    job: 'Community Mobilization Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Курпас Іван',
    email: 'spilinitsiatyv@gmail.com',
    job: 'Community Mobilization Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Бочкова Оксана',
    email: 'oksanabochcova889@gmail.com',
    job: 'Community Mobilization Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Бондар Тамара',
    email: 'jetod1908@gmail.com',
    job: 'Community Mobilization Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Анастасія Зацаринна',
    email: 'a.zatsarynna@lampa.ngo',
    job: 'Finance Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Микита Павлютін',
    email: 'Pavliutin_mykyta@pomogaem.com.ua',
    job: 'MEAL specialist',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Савченко Дмитро',
    email: 'savchenkodmitriy0603@gmail.com',
    job: 'Safety Officer',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Антонова Тамара',
    email: 'antonovatamara83@gmail.com',
    job: 'Driver',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Ілля Віскрівенко',
    email: 'Pabg4299@gmail.com',
    job: 'Field Coordinator',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Наталія Медведєва',
    email: 'nmedvedeva76@gmail.com',
    job: 'Radio Operator',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Яків Рябошапка',
    email: 'yakivryaboshapka@gmail.com',
    job: 'Field Coordinator',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Микита Павлютін',
    email: 'nmedvedeva76@gmail.com',
    job: 'MEAL Specialist',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Тетяна Чернікова',
    email: 'tetyana.chernikova@greenlandiya.org',
    job: 'Project Manager',
    nameOrg: 'Green-Landiya',
  },
  {
    fullName: 'Левенець Сергій',
    email: 'nastia151602@gmail.com',
    job: 'Driver',
    nameOrg: 'Green-Landiya',
  },
  {
    fullName: 'Наталія Гавря',
    email: 'natalia.gavria@greenlandiya.org',
    job: 'Finance Specialist',
    nameOrg: 'Green-Landiya',
  },
  {
    fullName: 'Денисенко Валентин',
    email: 'Greenlandiya.GO@gmail.com',
    job: 'Head',
    nameOrg: 'Green-Landiya',
  },
  {
    fullName: 'Микита Денисенко',
    email: 'Mykyta.denysenko@greenlandiya.org',
    job: 'Project Manager',
    nameOrg: 'Green-Landiya',
  },
  {
    fullName: 'Вікторія Ремша',
    email: 'viktoriia.remsha@greenlandiya.org',
    job: 'Communications Manager',
    nameOrg: 'Green-Landiya',
  },
  {
    fullName: 'Дарина Баранова',
    email: 'daryna.baranova@greenlandiya.org',
    job: 'Head of program',
    nameOrg: 'Green-Landiya',
  },
  {
    fullName: 'Данило Возруд',
    email: 'd.vozrud@gmail.com',
    job: 'Instructor',
    nameOrg: 'Green-Landiya',
  },
  {
    fullName: 'Олена Ткачова',
    email: 'olena.tkachova84@ukr.net',
    job: 'Information Management Specialist',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Ганна Рубан',
    email: 'hanna_ruban@rcc-ua.org',
    job: 'Demining Team Leader',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: "Дар'я Євлахова",
    email: 'daraevlahova.2024@gmail.com',
    job: 'Demining Assistant',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Дарʼя Гриньова',
    email: 'grindasha2503@gmail.com',
    job: 'Demining Assistant',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Вікторія Єлізєва',
    email: 'viktoria091990@gmail.com',
    job: 'Humanitarian Mine Action Assistant',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Костя Рябуха',
    email: 'rabkonstantin95@gmail.com',
    job: 'Humanitarian Mine Action Specialist',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Великий Олександр',
    email: 'oleksandr_velykyi@rcc-ua.org',
    job: 'Humanitarian Mine Action Specialist',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Олександр Мальцев',
    email: 'oleksandr_maltsev@rcc-ua.org',
    job: 'Humanitarian Mine Action Specialist',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Анна Васильєва',
    email: 'annavasil04@gmail.com',
    job: 'Humanitarian Mine Action Assistant',
    nameOrg: 'Charitable organization “Relief Coordination Centre”',
  },
  {
    fullName: 'Щур Андрій',
    email: 'endrushchur@gmail.com',
    job: 'Lawyer',
    nameOrg: 'Lviv Mediation Centre',
  },
  {
    fullName: 'Анна Лиско',
    email: 'lysko.anya@gmail.com',
    job: 'Director',
    nameOrg: 'Lviv Mediation Centre',
  },
  {
    fullName: 'Марина Саєнко',
    email: 'samaig@ukr.net',
    job: 'Trainer',
    nameOrg: 'Lviv Mediation Centre',
  },
  {
    fullName: 'Караваєва Наталія',
    email: 'karavaieva.natali@mistosyly.org',
    job: 'Communications manager',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Дмитро Сусак',
    email: 'Dmytro.S@mistosyly.org',
    job: 'Head of Regional Office',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Дмитро Петрушин',
    email: 'd.petrushin@mistosyly.org',
    job: 'Lawyer',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Чернишев Андрій',
    email: 'achernyshev@ga.net.ua',
    job: 'Head of Advocacy and External Communications',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Танасійчук Віталій',
    email: 'vtanasiichuk@ga.net.ua',
    job: 'Project Assistant',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Щоголь Данило',
    email: 'dshchohol@ga.net.ua',
    job: 'PR and Communications Consultant',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Хоменчук Андрій',
    email: 'ahomenchuk@ga.net.ua',
    job: 'Accountant',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Маковецька Ліна',
    email: 'lmakovetska@ga.net.ua',
    job: 'Procurement Manager',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Маліков Василь',
    email: 'vmalikov@ga.net.ua',
    job: 'Area Coordinator Kharkiv',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Призенко Вадим',
    email: 'vpryzenko@ga.net.ua',
    job: 'Area Coordinator Lviv',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Пономаренко Дмитро',
    email: 'dponomarenko@ga.net.ua',
    job: 'Area Coordinator Dnipro',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Тихий Микита',
    email: 'mtykhyi@ga.net.ua',
    job: 'Social Worker Dnipro',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Худолєй Олексій',
    email: 'okhudoliei@ga.net.ua',
    job: 'Social Worker Kharkiv',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Харатін Андрій',
    email: 'akharatin@ga.net.ua',
    job: 'Social Worker Lviv',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Лугова Олена',
    email: 'oluhova@ga.net.ua',
    job: 'Supply Chain Assistant',
    nameOrg: 'Public organization "ALLIANCE.GLOBAL"(РО ""ALLIANCE.GLOBAL")',
  },
  {
    fullName: 'Daria Malinnikova',
    job: 'Lawyer',
    email: '',
    nameOrg: 'Non-Governmental Organization "Institute of Analytics and Advocacy"',
  },
  {
    fullName: 'Dmytro Piddubnyi',
    job: 'Lawyer',
    email: '',
    nameOrg: 'Non-Governmental Organization "Institute of Analytics and Advocacy"',
  },
  {
    fullName: 'Vladyslava Lomakina',
    job: 'Lawyer',
    email: '',
    nameOrg: 'Non-Governmental Organization "Institute of Analytics and Advocacy"',
  },
  {
    fullName: 'Аліфіренко Антон',
    job: 'Head',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Євтушенко Діана',
    job: 'Project Manager',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Мундурс Юрій',
    job: 'Finance Manager',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Гаврилець Ольга',
    job: 'Project Manager',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Зельманович Олена',
    job: 'Procurement Specialist',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Філон Ірина',
    job: 'Communications Manager',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Зацаринна Анастасія',
    job: 'MEAL Specialist',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Дмитренко Жанна',
    job: 'CFM Specialist',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Щербакова Анна',
    job: 'Community Mobilization Specialist',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Децюк Тетяна',
    job: 'Community Mobilization Specialist',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Бондар Тамара',
    job: 'Community Mobilization Specialist',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Душин(Курпас) Катерина',
    job: 'Community Mobilization Specialist',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Мазур Олена',
    job: 'Project Assistant',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Хуторянський Єгор',
    job: 'Project Assistant',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Савицька Світлана',
    job: 'Project Assistant',
    email: '',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Мося Денис',
    email: 'd.mosya@lampa.ngo',
    job: 'MEAL Specialist',
    nameOrg: 'Non-Governmental Organization "LAMPA" (NGO "LAMPA")',
  },
  {
    fullName: 'Світлана Ільницька',
    email: 's.v.ilnytska@gmail.com',
    job: 'Trainer',
    nameOrg: 'Lviv Mediation Centre',
  },
  {
    fullName: 'Олена Лиско',
    job: 'Accountant',
    email: '',
    nameOrg: 'Lviv Mediation Centre',
  },
  {
    fullName: 'Анастасія Осипова',
    email: 'a.work25@ukr.net',
    job: 'Registrar',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Ольга Нагорянська',
    email: 'olganagoranskaa@gmail.com',
    job: 'Field Operator',
    nameOrg: 'Cheritable Fund "Pomogaem" (CF "Pomogaem")',
  },
  {
    fullName: 'Аліна Федорова',
    email: 'a.fedorova@mistosyly.org',
    job: 'Distribution Specialist',
    nameOrg: '"Misto Syly" Non-governmental organization"("Misto Syly" NGO")',
  },
  {
    fullName: 'Анна Крамар',
    email: 'anuta__m@ukr.net',
    job: 'MEAL manager',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
  {
    fullName: 'Ольга Хоружа',
    email: 'olga.masalitova@gmail.com',
    job: 'Trainer',
    nameOrg: 'Non-governmental organization "League of Modern Women" ("League of Modern Women".NGO)',
  },
]
