name: '[Server] Build & Deploy to Azure'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Clean
        run: |
          rm -rf ./packages/infoportal-client
          rm -rf ./packages/infoportal-script

      - name: Install dependencies
        run: |
          npm ci

      - name: Build, and test (common)
        working-directory: ./packages/infoportal-common
        run: |
          npm run build --workspace infoportal-common --if-present
          npm run test --workspace infoportal-common --if-present

      - name: Generate Prisma schema and copy engines
        run: |
          # Generate Prisma client
          npm run db-generate

      - name: Copy Prisma client to server package
        run: |
          echo "Copying generated Prisma client to server package..."
          # Define source (root node_modules) and destination (package node_modules)
          PRISMA_CLIENT_SOURCE="./node_modules/.prisma/client"
          PRISMA_CLIENT_DEST="./packages/infoportal-server/node_modules/.prisma/client"

          # Ensure destination directory exists
          mkdir -p "$PRISMA_CLIENT_DEST"

          # Copy the generated client files and binaries
          rsync -a "$PRISMA_CLIENT_SOURCE"/ "$PRISMA_CLIENT_DEST"/

          echo "Verifying copied files:"
          ls -l "$PRISMA_CLIENT_DEST"

      - name: Build, and test (server)
        working-directory: ./packages/infoportal-server
        run: |
          npm run build --workspace infoportal-server --if-present
          npm run test --workspace infoportal-server --if-present

      - name: Update deployment tag
        run: |
          TAG_NAME="deployed_server"

          echo "Delete the tag locally if it exists"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Deleting existing tag $TAG_NAME"
            git tag -d "$TAG_NAME"
          fi

          echo "Creating tag $TAG_NAME at commit $GITHUB_SHA"
          git tag "$TAG_NAME" "$GITHUB_SHA"

      - name: Zip and prepare release artifact
        working-directory: ./packages/infoportal-server
        run: |
          zip -r release.zip dist package.json package-lock.json node_modules prisma host.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./packages/infoportal-server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'drc-imaa-ukr-tools-api'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_498AC70480F04DF09CF86CBF3D15E5B2 }}
