# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: "[Client] Build & Deploy to Azure - drc-imaa-ukr-tools"

on:
  #  push:
  #    branches:
  #      - main
  workflow_dispatch:

env:
  NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
  NEXT_PUBLIC_APP_OFF: ${{ secrets.NEXT_PUBLIC_APP_OFF }}
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
  NEXT_PUBLIC_GOOGLE_MAPS_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_ID }}
  NEXT_PUBLIC_MS_AUTHORITY: ${{ secrets.NEXT_PUBLIC_MS_AUTHORITY }}
  NEXT_PUBLIC_MS_BEARER_TOKEN: ${{ secrets.NEXT_PUBLIC_MS_BEARER_TOKEN }}
  NEXT_PUBLIC_MS_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_MS_CLIENT_ID }}
  NEXT_PUBLIC_MUI_PRO_LICENSE_KEY: ${{ secrets.NEXT_PUBLIC_MUI_PRO_LICENSE_KEY }}
  IGNORE_BUILD_TS_ERRORS: ${{ secrets.IGNORE_BUILD_TS_ERRORS }}
  PORT: ${{ secrets.PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    #    defaults:
    #      run:
    #        working-directory: ./infoportal-client

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test (kobo-sdk)
        working-directory: ./packages/kobo-sdk
        run: |
          npm ci --production
          npm run build --if-present
          npm run test --if-present

      - name: npm install, build, and test (library)
        working-directory: ./packages/infoportal-common
        run: |
          npm ci --production
          npm run build --if-present
          npm run test --if-present

      - name: npm install, build, and test (library)
        working-directory: ./packages/infoportal-client
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_APP_OFF: ${{ vars.NEXT_PUBLIC_APP_OFF }}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
          NEXT_PUBLIC_GOOGLE_MAPS_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_ID }}
          NEXT_PUBLIC_MS_AUTHORITY: ${{ secrets.NEXT_PUBLIC_MS_AUTHORITY }}
          NEXT_PUBLIC_MS_BEARER_TOKEN: ${{ secrets.NEXT_PUBLIC_MS_BEARER_TOKEN }}
          NEXT_PUBLIC_MS_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_MS_CLIENT_ID }}
          NEXT_PUBLIC_MUI_PRO_LICENSE_KEY: ${{ secrets.NEXT_PUBLIC_MUI_PRO_LICENSE_KEY }}
          IGNORE_BUILD_TS_ERRORS: ${{ secrets.IGNORE_BUILD_TS_ERRORS }}
          PORT: ${{ secrets.PORT }}
        run: |
          npm ci --production
          npm run build --if-present
          npm run test --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        working-directory: ./packages/infoportal-client
        run: zip release.zip package.json .next/standalone ./next/static -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./packages/infoportal-client/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'drc-imaa-ukr-tools'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3A2F703F950A4017B78DC40A1C071B87 }}