# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: "[Server] Build & Deploy to Azure"

on:
  #  push:
  #    branches:
  #      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Clean
        run: |
          rm -rf ./packages/infoportal-client
          rm -rf ./packages/infoportal-script

      - name: Install
        run: |
          npm ci

      - name: npm install, build, and test (kobo-sdk)
        working-directory: ./packages/kobo-sdk
        run: |
          npm run build --workspace kobo-sdk --if-present
          npm run test --workspace kobo-sdk --if-present

      - name: Build, and test (common)
        working-directory: ./packages/infoportal-common
        run: |
          npm run build --workspace infoportal-common --if-present
          npm run test --workspace infoportal-common --if-present

      - name: Build, and test (server)
        working-directory: ./packages/infoportal-server
        run: |
          npm run db-migrate
          npm run build --workspace infoportal-server --if-present
          npm run test --workspace infoportal-server --if-present

      - name: Zip
        working-directory: ./packages/infoportal-server
        run: zip release.zip dist/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./packages/infoportal-server/release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'drc-imaa-ukr-tools-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_498AC70480F04DF09CF86CBF3D15E5B2 }}
